### ISSUE TITLE
Coordinates are displayed wrong in the latest master

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/QWAT#104]
@3nids I just noticed this morning the coordinate numbers were wrong for my localized QWAT project.

I also looked at the default project (21781 SRID) and it also gives wrong coordinates: ``6.8541,46.3837``.
As I just tested under Windows also, this seems an upstream issue.
However, I cannot replicate the issue if I open a new project and add layers.

Did you notice this?
![problem](https://cloud.githubusercontent.com/assets/3179646/13177934/d6da1c4a-d724-11e5-8f86-1196112de728.png)

**Comment by 3nids** [comment]
I think you just need to disable OTF.
I'll do it asap (monday) on project and push.
In the mean time, can you check if it works for you?

**Comment by tudorbarascu** [comment]
This issue is with OTF disabled (In project properties and in options settings), I also tested upon restarting QGIS just to be sure.
Moreover, all my layers are in the same projection as the project, so even with OTF enabled, it shouldn't have been the case for any reprojection.

**Comment by tudorbarascu** [comment]
It seems the issue was already signaled here: https://hub.qgis.org/issues/14319
Maybe there are some leftovers in the .qgs XML or the issue was not fixed in the https://github.com/qgis/QGIS/commit/800b521231b3655513c311a9578da0390dff2962 commit.
