### ISSUE TITLE
label_2_visible set to false by default instead of NULL

### ISSUE THREAD

**Issue by ponceta** [qwat/QWAT#108]
Creating a new valve item generates a "false" value under the column label_2_visible which makes the saves impossible since integer is expected.

Does not appends when creating from the imported view (not the one set by default on the project).

Trying to fix it through ui forms/valve.ui via qt or .qgs project but did not manage to find a simple workaround yet.

Any hints are welcome!

**Comment by ponceta** [comment]
Does not come from the ui form.

**Comment by ponceta** [comment]
Found it : 

Need to replace the wrong edittype for label_2_visible under the .qgs project under vw_element_valve into something like that

<edittype widgetv2type="ValueRelation" name="label_2_visible">
  <widgetv2config OrderByValue="0" AllowNull="0" FilterExpression="" UseCompleter="0" fieldEditable="1" Key="vl_code_int" Layer="vl_visible20130304110011703" Value="value_fr" labelOnTop="0" AllowMulti="0"/>
</edittype>

**Comment by tudorbarascu** [comment]
Hi, I cannot reproduce on master, so either the issue was present at one point in time or you modified the project somehow. Thus, a link to your zipped project + empty db model  (or optionally the latest commit in your data model) would shed some light.

**Comment by ponceta** [comment]
Solved : value was not set as relationnal

![image](https://cloud.githubusercontent.com/assets/8614223/13452906/7c44e43c-e04c-11e5-988d-0f994a5a62e4.png)
