### ISSUE TITLE
Saved hydrants, valves, ... are not snapable with CadTools

### ISSUE THREAD

**Issue by ponceta** [qwat/QWAT#111]
I've not send an issue to https://github.com/geopython/CadTools yet because I wanted to have your feedbacks on this issue:

When editing hydrants, valves or installation parts, snapping tool from cadtool is very useful.

![image](https://cloud.githubusercontent.com/assets/8614223/13746809/6c8611e4-e9f5-11e5-9b0e-0243dbd37e35.png)

But once the feature has been saved. The snapping tool is disabled for this feature (until next feature load on project reopenning)

![image](https://cloud.githubusercontent.com/assets/8614223/13746887/d6f818c4-e9f5-11e5-904c-f493836fb306.png)

The only workaround I've found yet is to keep features in edit mode.

This only happens on views and not on tables. But table elements generated from views have the same issue. (first idea was to keep all nodes table active)

**Comment by 3nids** [comment]
no idea, I don't any trouble with Advanced Digitizing tools.
it's a bit weird to me.

**Comment by ponceta** [comment]
This is really a CadTool related issue. I tried with cadtools deactivated and it worked.
I'll try to go deeper since cadtools offers some appreciated geometrical operations.
mentionned in https://github.com/geopython/CadTools/issues/21

**Comment by vpicavet** [comment]
If this is CadTool related, closing for now here. Reopen if you find some qWAT-specific problematic behaviour.
