### ISSUE TITLE
Tool to compute interpolated elevation for network elements

### ISSUE THREAD

**Issue by vpicavet** [qwat/QWAT#113]
We need a tool allowing the user to click on a network element and compute an interpolated elevation value given surrounding Z measurements ( on nodes and survey points).

This would be a maptool with some parameters ( to be refined, add your comments below ) : 
- tolerance distance for survey points
- and/or number of survey points to take into account

**Comment by mhugo** [comment]
I see how to interpolate between two points, but when there are more than 2 points, what to do ? An average ?

**Comment by mhugo** [comment]
About interpolation given multiple points on an irregular grid :
http://math.stackexchange.com/questions/828392/spatial-interpolation-for-irregular-grid

**Comment by dsavary** [comment]
Look at the tool "Interpolate" in this plugin : [VDLTools](https://github.com/gusthiot/VDLTools)

**Comment by haubourg** [comment]
Decision PSC 06/10/2016 agrees on keeping such features in VDL Tool plugin.
