### ISSUE TITLE
Tool to create node or survey points with elevation

### ISSUE THREAD

**Issue by vpicavet** [qwat/QWAT#115]
A complementary tool on top of #113 and #114 would allow the user to : 
- create a node or a survey point at a specific location
- set the elevation value at this point : manually, nearest vertex value, interpolated value from nearest object

**Comment by dsavary** [comment]
Look at the tool "Interpolate" and "Profile" in this plugin : VDLTools
It can help us to handle the altitude (coordinate Z) of the network element in QGIS.

**Comment by haubourg** [comment]
Decision PSC 06/10/2016 agrees on keeping such features in VDL Tool plugin.
