### ISSUE TITLE
Add SQL methods to revert changes ( undo history feature)

### ISSUE THREAD

**Issue by vpicavet** [qwat/QWAT#116]
Following discussion on log ( #77 ), next step would be to add methods to revert some changes in SQL.

See the issue on data model for a list of actions to take into account : qwat/qwat-data-model#112

**Comment by 3nids** [comment]
we have some interest from others to develop a solution
see https://github.com/3nids/postgres91plusauditor/issues/9

**Comment by sylvainbeo** [comment]
In progress
