### ISSUE TITLE
GUI for history of changes and revert actions

### ISSUE THREAD

**Issue by vpicavet** [qwat/QWAT#117]
Following discussion on logs ( #77 ), it would be nice to have a clean GUI to access history and be able to revert changes.

This requires #116 to be implemented first.

**Comment by sylvainbeo** [comment]
In progress

**Comment by ponceta** [comment]
Done and WIP? should be closed!

**Comment by haubourg** [comment]
No, switched back to "Review",  we lack testing to close that so soon
