### ISSUE TITLE
End-user scenarios for automated testing

### ISSUE THREAD

**Issue by vpicavet** [qwat/QWAT#119]
We need to define end user scenarios for 2nd level testing.

This would be a set of actions done by a user when using qWAT. 
These actions will then be written as SQL commands and tested against the result.

**Comment by vpicavet** [comment]
This can be an opportunity to write the end-user documentation at the same time

**Comment by sylvainbeo** [comment]
These tests have been added. They also will be used to make the stress tests for the DB
