### ISSUE TITLE
Specify which CAD features are needed for qWAT

### ISSUE THREAD

**Issue by vpicavet** [qwat/QWAT#122]
This is a end-user specification issue.

We need to know what kind of CAD tools are needed for qWAT.
Then we will need to compare to existing CAD QGIS features & plugins
A global discussion with the community will also be required
Then we will be able to draw a global plan for CAD tools improvement in QGIS satisfying qWAT needs.

Add your needs in comment here

linked issues:

- [x]  - https://github.com/qwat/QWAT/issues/136 
- [x]  - https://github.com/qwat/QWAT/issues/147
~~- [ ]  - https://github.com/qwat/QWAT/issues/193~~ Not specifically a CAD tool. 
- [x]  - https://github.com/qwat/QWAT/issues/146

**Comment by haubourg** [comment]
Closing,. 
Will open new issues related to opened QEPs and user's request in 2018
