### ISSUE TITLE
Windows installer

### ISSUE THREAD

**Issue by vpicavet** [qwat/QWAT#123]
Most newcomers use windows. qWAT should therefore be easy to install on Windows, and installation documentation should be written for this OS.

There are currently some hard points when installing on Windows ( e.g. shell scripts).
First step is to list them here, and then implement an installation process

**Comment by haubourg** [comment]
PSC 06/10 has no internal need. This point is being raised from users outside of PSC. 
This point must be discussed as part of the communication - spreading policy of QWAT.

**Comment by haubourg** [comment]
New full data sample 1.2.0 with structure and data allows that. 
Now we need to make the doc with pgadmin screencasts

**Comment by haubourg** [comment]
since #178, several dump files are available allowing to deploy QWAT without using the init script. Closing the issue
