### ISSUE TITLE
Multi-object edition tool

### ISSUE THREAD

**Issue by vpicavet** [qwat/QWAT#125]
A tool allowing to edit geometries for multiple objects would be interesting.
E.g. edit a node and geometrically move the attached pipes.

**Comment by 3nids** [comment]
this might be attached to Martin's dev for the node tool?

**Comment by m-kuhn** [comment]
We have discussed some ideas regarding this. Basically the idea would be to select multiple layers in the legend and then update a maptool/the maptools to be able to work with this.
It would be great to get more feedback for them.

**Comment by haubourg** [comment]
CLosing, PSC 10/06 did not raise a real need in that area
