### ISSUE TITLE
CAD DWG/DXF import and editing

### ISSUE THREAD

**Issue by vpicavet** [qwat/QWAT#127]
Importing plans from Autocad format is important.
Importing and directly using DWG/DXF files is a plus for qWAT.

This is already a work in progress funded by Andreas Neumann and implemented by Jurgen Fischer

**Comment by haubourg** [comment]
For the record, another dxf importer plugin just landed http://plugins.qgis.org/plugins/AnotherDXF2Shape/
It seems to add interesting feature. 
@qwat-psc can someone test it with real dxf? Could someone send me a sample dxf for testing purposes? thanks
----------------
Features:
- Other elements than the standard import are displayed
- Display of text (Labeling)
- Text parameters (attributes) are convert from the DXF (E.g. Rotation angle, text size, text color, position (text-align), color)
- transfer of individual text formats

- Categorization by Layer
- Group by Layer
- Separate representation by layers possible
- optional: convert color from DXF

**Comment by haubourg** [comment]
Even better : https://twitter.com/neogis_de/status/809692441204977664

DWG core importer landed in qgis 2.18.2 and 2.99! Tested here and it renders really nice. Data is imported into a GPKG. 
Tests more than welcome, this can be usefull for your workflows @qwat-board

**Comment by jef-n** [comment]
On Wed, 21. Dec 2016 at 03:05:35 -0800, Régis Haubourg wrote:
> Even better : https://twitter.com/neogis_de/status/809692441204977664

https://github.com/qgis/QGIS/commit/a85fe1fa4464e5b6f7bd7e9dbb76c679ec75ec29

Jürgen

-- 
norBIT Gesellschaft fuer Unternehmensberatung und Informationssysteme mbH
Rheinstrasse 13, 26506 Norden
GF: Jelto Buurman, HR: Amtsgericht Aurich HRB 100827

**Comment by haubourg** [comment]
Thanks Jurgen ! Do know if libdxfrw devs have plans for write capabilities on dwg?  (I'm probably dreaming of a sort of a encrypted and compressed holy grail which is changing every 3 years.. )

**Comment by haubourg** [comment]
@Board Current dwg import works nicely, is that enough to close that qwat issue?

**Comment by SSGoveia** [comment]
Any news about importing DXF into the QWAT data model?
