### ISSUE TITLE
slider to set DPI

### ISSUE THREAD

**Issue by vpicavet** [qwat/QWAT#129]
We have some use cases for changing the DPI dynamically in the canvas : 
* 4K ( and more ) display
* editing small items at a specific zoom level displayed bigger on the screen

**Comment by vpicavet** [comment]
The main use case is to be able to see the canvas with an image zoom ( as opposed to a geographical zoom). DPI slider for canvas is a way to achieve this, and can be really useful for high-resolution screens.

Another option could be a magnifier tool.

**Comment by mhugo** [comment]
QT has probably a way to handle large displays and sets the DPI, but I cannot find it ...
Alternatively we can add a slider to zoom the canvas.
Do we want everything to be zoomed ? Or only texts / labels / diagrams ?

**Comment by 3nids** [comment]
the idea is to magnify the whole map as if we were using a magnifier

**Comment by mhugo** [comment]
@3nids Is it a pixel-based zoom that is needed ? Or a "real" zoom where vector features (and possibly symbology) would be zoomed ?
I cannot see the added value of a pure pixel-based zoom compared to say ... the integrated "magnifier" tool of Windows for instance.

**Comment by 3nids** [comment]
yes it would a pixel-based zoom on the map canvas only.
I don't know the magnifier on windows, but as far as I see it, the advantage is that the zoom will be applied strictly and only on the map canvas.
One use case is the manual placement of labels. We have very small labels and it is very painful for the eyes to work at 1:1. Being able to have a 2x zoom would be very helpful.
Does it make sense to you?

**Comment by mhugo** [comment]
Ok. So you need a zoom that follows the mouse and let you do other actions (label placement for instance).
Would it be wrong if it is a vector-based zoom ? (no "big pixels" when you zoom)

**Comment by vpicavet** [comment]
If we need to do actions while having the zoom, the DPI slider seems better.
Last remaining question would be pixel-based versus vector-based zoom.
And in case of pixel based, do we want pixelized zoom ( nearest neighbour ) or interpolation ( e.g. bilinear )

**Comment by pblottiere** [comment]
> If we need to do actions while having the zoom, the DPI slider seems better.

:+1: 

> And in case of pixel based, do we want pixelized zoom ( nearest neighbour ) or interpolation ( e.g. bilinear )

We could provide to the user a simple way to set the desired method.

**Comment by 3nids** [comment]
I thought at beginning that the whole map canvas would be zoomed. Although, a window around the map also has it advantages, and most important might avoid confusions between the two ways to "zoom".
I would go for interpolation without adding any option. The cost might not be that bad no?

**Comment by pblottiere** [comment]
PR submitted : https://github.com/qgis/QGIS/pull/3009

**Comment by 3nids** [comment]
thanks.
will you go for DPI rather than pixel-based?

**Comment by pblottiere** [comment]
@3nids Indeed, it seems that a DPI magnifier is what they REALLY want. However, it's not the initial request and when I took a look to mapsettings, I noticed some strange behaviours with DPI. So, I need more time than the time initially allocated to this item. Do you agree?

**Comment by 3nids** [comment]
Well this not m decision to take, but from the discussion there doesn't seem to be much of a choice.
So, for me yes, this is the way to go.

**Comment by vpicavet** [comment]
Merged in master. Closing ?
