### ISSUE TITLE
Fix some DXF export bugs and enhance features

### ISSUE THREAD

**Issue by vpicavet** [qwat/QWAT#130]
- [ ] data-defined properties are not taken into account, at least for line width, and SVG symbol orientation
- [ ] rule-based labelling is not working on export
- [ ] 3D is not taken into account

Jurgen would be the best candidate for developing this

**Comment by jef-n** [comment]
See also [QGIS #13757](http://hub.qgis.org/issues/13757) and [QGIS #14495](http://hub.qgis.org/issues/14495)

**Comment by jef-n** [comment]
3D support: qgis/QGIS@b3bf4a1

**Comment by vpicavet** [comment]
Great ! Thanks Jef
