### ISSUE TITLE
QWAT naming convention

### ISSUE THREAD

**Issue by 3nids** [qwat/QWAT#132]
QWAT is currently being written as qwat, QWAT, qWat.
We should stick to one. I'm not a huge fan of the last, I would go for all in capital letters.
What do you think?

**Comment by sylvainbeo** [comment]
Why not. But the name may potentially change in the futur. Anyway, i'm ok with all writing.

**Comment by vpicavet** [comment]
I'm ok with all capitals, the main idea would be for people to catch easily that the name is pronounced "cue-what"

Other options could be qWAT or Qwat in that sense.

**Comment by sylvainbeo** [comment]
Indeed. I've met a few people who do not know how to pronounce it.

**Comment by ponceta** [comment]
https://translate.google.com/#fr/sq/QWAT

Ca sonne vraiment différemment selon d'où on vient...

**Comment by DanBing** [comment]
Je confirme ...

https://translate.google.com/#pl/sq/QWAT




De :    Arnaud Poncet-Montanges <notifications@github.com>
A :     qwat/QWAT <QWAT@noreply.github.com>
Date :  03.06.2016 15:02
Objet : Re: [qwat/QWAT] QWAT naming convention (#132)



https://translate.google.com/#fr/sq/QWAT
Ca sonne vraiment différemment selon d'où on vient...
?

**Comment by 3nids** [comment]
let's decide this on monday.

**Comment by haubourg** [comment]
I guess the decision was made to "QWAT". Can we close this?
