### ISSUE TITLE
copy and offset a line

### ISSUE THREAD

**Issue by dsavary** [qwat/QWAT#133]
The user could select 3D polyline and give it a offset length  (choice of the side where the line should be offset). The user can choose if he wants to offset the selection or offset a copy of the selection. If it choose the copy, the feature must keep the same attributes , except the ID and if it's possible the same number of vertices.

start development : @gusthiot
Link : [https://github.com/gusthiot/VDLTools/tree/master/tools](url)

**Comment by 3nids** [comment]
This is already feasible using copy/paste then offset.

I would propose to extend the paste action, and have options:

* paste and move
* paste and rotate
* paste and offset

See issues #138 and #139

**Comment by dsavary** [comment]
Development in progress , you can look the code here VDLTools
Please test the tool and report the bug.
At the moment, we create only one tool bar for several tool.
For a generic use, we could split this tool bar in several block of plugin

**Comment by dsavary** [comment]
Is there any news about developments in QGIS Core for this functionality?
For which version of QGIS ?

**Comment by 3nids** [comment]
I would like to add this option to the move feature tool. You would have the choice: paste and move or just move. This shouldn't be too hard to implement :)

**Comment by haubourg** [comment]
PSC 06/10: good to keep in wishlist for CAD tool refactoring.

**Comment by haubourg** [comment]
Done in QGIS 3 by @3nids
