### ISSUE TITLE
create a vertex in a 2D or 3D line automatically when the user create a point.

### ISSUE THREAD

**Issue by dsavary** [qwat/QWAT#135]
Description of the tool :
When the user creates a point over a 2D or 3D line (by using edge snapping), a vertex is automatically created. The tool calculates the 3D elevation for the vertex line and the 3D point (interpolation). When the user creates a point over an existing vertex of a 3D line, the altitude of the point takes automatically the same altitude as the vertex.
#115

**Comment by dsavary** [comment]
Development in progress , you can look the code here [VDLTools](https://github.com/gusthiot/VDLTools) 
Please test the tool and report the bug. 
At the moment, we create only one tool bar for several tool. 
For a generic use, we could split this tool bar in several block of plugin

**Comment by dsavary** [comment]
Is there any news about developments in QGIS Core for this functionality?
For which version of QGIS ?

**Comment by 3nids** [comment]
I am not aware of anything but it's not a topic I follow closely.

**Comment by dsavary** [comment]
In the case that the user check the option "topology snap" in the snapping settings of the QGIS project, it would be nice that a vertex is automatically created at the intersection between points and lines (or points on the polygon perimeter ) .
@haubourg do you think that it can be done in QGIS core or it's too specific ? 
If no, we can close this issue.

**Comment by haubourg** [comment]
@dsavary I think this is too specific to our business logic. To me, this belongs to the database API logic. 

Some can argue differently, but if we go that way with QGIS core, we should add an option to enable that in the snapping dialog. The same stands for the "multi layer" node tool editing capabilities. Some want to keep different layers in sync, some don't. As long as it's easy to finely control that on the DB side of things, I'm in favour of closing that issue and open a new one on concerning the DB API.
