### ISSUE TITLE
Create a circle according to a dimension (slightly different behavior of the plugin "intersect it")

### ISSUE THREAD

**Issue by dsavary** [qwat/QWAT#136]
Description of the tool :
create a circle according to a given radius (dimension), then you can create a point in a choice layer by snapping only on the intersection (no snapping on vertices ) - the functioning is close to the plugin "intersect it" (except : choice of interactive layer when creating the intersection point, disable the snapping option on the  vertices of circle, only activate the snapping on intersection).

**Comment by dsavary** [comment]
Development in progress , you can look the code here [VDLTools](https://github.com/gusthiot/VDLTools) 
Please test the tool and report the bug. 
At the moment, we create only one tool bar for several tool. 
For a generic use, we could split this tool bar in several block of plugin

**Comment by dsavary** [comment]
For this tool, we test to use a circle geometry, but the "basic snapping options" of QGIS doesn't allow to snap at the intersection between a linestring and a circularstring.

**Comment by haubourg** [comment]
PSC 10/06 : should be solved in QGIS 3 since new snapping API snapps on all feature types. Old one wasn't aware of curved geometries. 
Still needs to be tested in QGIS 3 branch

**Comment by haubourg** [comment]
For the record, 
a new qgis contributor named L. Bartoletti is adding core classes to digitize circles, rectangles and ellipses in QGIS. 
see: https://lists.osgeo.org/pipermail/qgis-developer/2017-May/048605.html 

He seems to be the autor of QAD and CADDigitize plugin.

**Comment by haubourg** [comment]
Tested and approved using the new digitising toolbar for circles and the advanced digitising panel

![digitize_circle_by_distance](https://user-images.githubusercontent.com/1629853/37028630-1deefac2-2135-11e8-8e5e-4b58f62c38a4.gif)

Many thanks @lbartoletti !
