### ISSUE TITLE
additional snapping options

### ISSUE THREAD

**Issue by dsavary** [qwat/QWAT#137]
Description of the tool:
The user can activate additional snapping type : snap to a perpendicular line, snap to the extension of a line. the use of different symbol according to snap choice should indicate to the user what kind of snap option is active during the digitizing. For example, a green cross appear for a intersection snapping.  (Avoid errors of digitization)

**Comment by dsavary** [comment]
Is there any news about developments in QGIS Core for this functionality?
For which version of QGIS ?

**Comment by 3nids** [comment]
All this is already available in QGIS for quite some time with advanced digitizing tools.
case 1: Just use perpendicular and select the appropriate segment. 
case 2 is a bit more tricky: enable construction mode, place a point on the segment, place the mouse over it, lock the angle, disable construction mode. Next point will be aligned with the segment. If needed, this could added to the advanced digitzing dock to make it more straightforward.

**Comment by haubourg** [comment]
psc decision to close this ticket
