### ISSUE TITLE
Add visual feeback of snapping type

### ISSUE THREAD

**Issue by haubourg** [qwat/QWAT#147]
Users lack visual feedback of snapping type currently happening. Lausanne asks that different symbols can shown when snapping on vertex or segment. 
Additionnaly, having a visual indicator of which layer is snapped would be a great plus.

Ref https://issues.qgis.org/issues/15119

**Comment by haubourg** [comment]
discussion started here: http://osgeo-org.1560.x6.nabble.com/Snapping-visual-feedback-td5294666.html

**Comment by haubourg** [comment]
CR atelier du 14 décembre 2016. Pour Lausanne, le feedback visuel auquel sont habitués les dessinateurs est en priorité celui d'autocad avec confirmation visuelle du type de snapping : 
- vertex (rond)
- segment (carré)
- intersection (croix)

**Comment by dsavary** [comment]
About the visual feedback of snapping type, I think that we can use the same symbol as AutoCAD snapping tool. Many users are used to see these symbols. The use of different colors is not important, but why not. 
I think that it's important that we use "cross" for intersection snap and "circle" for vertex snap and that the symbol is perhaps larger than now in QGIS (as node tool).

About the different class of snapping, there is many snapping type in AutoCAD, perhaps too much . 
You can start with basic snapping type : vertex ,  segment , intersection (also between line and circular arc) and perhaps as second priority : mid point snap, center of circle snap , direct perpendicular snap.
Important : some snapping type must be given priority over others when there are several possibilities of snapping on the map. For example, I think that the intersection snap should be preferred as vertex snap. 

For the future, it will be good to have a support tool to choose on which layer the snapping tool is active.  :) in particular when we work with the 3D layers.

Some screenshots:
[https://share.oslandia.net/public/e814b6](https://share.oslandia.net/public/e814b6)
[center_snap](https://share.oslandia.net/public/bfef8c)
[mid_point_snap](https://share.oslandia.net/public/4639cd)
[perpendicular_snap](https://share.oslandia.net/public/e393ef)

**Comment by dsavary** [comment]
I tested the new snapping tool with QGIS 2.99 .
Some comments : 
- intersection snap seems to not work with 3d layer 
demo GIF : [https://share.oslandia.net/public/186efd](https://share.oslandia.net/public/186efd)
- add snap intersection between line (or polygon) and circular arc 

I think that it's important in the future that all CAD tools in QGIS use the same snapping symbols

**Comment by haubourg** [comment]
@wonder-sk 
Hi Martin, following yesterday's general QWAT meeting, we decided to  implement this year only the symbol change for vertex / endpoint / segment stuff. The interactive layer choice and snapping priorities won't make it in the budget for now and will be postponed to 2018. Did you start any real work in that area?

**Comment by dsavary** [comment]
@wonder-sk @haubourg 
Hi, but for Lausanne, it'is important that the basic snapping type "intersection" (display with a cross symbol) works between : 
- 2 lines
- 2 circular arcs
-  1 line and 1 circular arc 

the same for the intersections between the polygon edges

**Comment by dsavary** [comment]
After some tests on QGIS 2.99 , the snapping type "intersection" doesn't seem to be working well , even between 2 lines. It's impossible to snap precisely on the intersection.

**Comment by haubourg** [comment]
@wonder-sk Martin, is there anything new on this front, now that the feature freeze is getting closer (reminder was : implement the first part of visual snapping, only have symbol changing following the snapping type). Thanks for your feedback

**Comment by wonder-sk** [comment]
Hi @haubourg sorry for the delays as I got sidetracked with other duties. I have not started working on this bit yet. If we are talking about different visual indicators only, that should be hopefully straightforward to address. I am about to tak a few days off, but I think I could look into that during the next week...

**Comment by haubourg** [comment]
@wonder-sk Thanks for the update and enjoy the days off !

**Comment by ponceta** [comment]
Snapping on common nodes is quite natural IMHO, at least on QGIS 3. This could be enhanced by highlighting the node's polygon to be snapped. 

@haubourg said in https://github.com/qwat/QWAT/issues/218
> But yes, when you want to disjoin polygons, it's not easy to choose which polygon to grab currently I'm not clear on how to force which polygon to batch grab from a user point of view. any idea?

Isn't there already actually some mechanism that prefer one polygon to be snapped, because I could reproduce some systematic snapping to the desired polygon (see gif here under)

![snapping_common_nodes](https://user-images.githubusercontent.com/8614223/31075251-e972841a-a774-11e7-906b-3f551132750c.gif)

**Comment by dsavary** [comment]
News about this issue ?

**Comment by haubourg** [comment]
@wonder-sk told me it was on the list.

**Comment by haubourg** [comment]
@wonder-sk I tested the new visual snapping option, great!
two questions:
- I couldn't have the "intersection" snapping option working. Do you have that issue too?
- The icon sizes are small, i don't see them well under the edit cursor. Is it configurable somewhere?

**Comment by wonder-sk** [comment]
> I couldn't have the "intersection" snapping option working. Do you have that issue too?

Just checked and it seems to work fine for me - I get a cross indicator where it should be. Does it mean that for you the snapping on intersection does not work at all? (Have you enabled it in snapping options?)

> The icon sizes are small, i don't see them well under the edit cursor. Is it configurable somewhere?

Do you have a high DPI display? The icon sizes are in pixels currently, so they may look a bit small with high DPI. It is not configurable anywhere right now. But maybe it would be good to update the vertex marker API to accept icon size / pen width in millimeters as well - just like in map rendering - and use that as a default to get consistent results everywhere...

**Comment by haubourg** [comment]
Ok, rechecked twice and all good !
Thanks a lot Martin !
