### ISSUE TITLE
ouvrage form is broken in attribute table / form view

### ISSUE THREAD

**Issue by haubourg** [qwat/QWAT#152]
in QGIS master and release, form view accessible from attribute table is truncated. The conditional part showing different widgets according to ouvrage type is not displayed correctly. 
Same form open outside from attribute table works. 

Tracing init function installation_form.py shows that it is triggered for each table row every time user select another feature. This can be a killer for big tables. Not sure why widget display is not done correctly in this case

**Comment by haubourg** [comment]
@mhugo could you check if this is a core issue or a python init script issue? Thanks

**Comment by haubourg** [comment]
here a snapshot of the broken form
 ![capture d ecran de 2016-10-12 09-18-11](https://cloud.githubusercontent.com/assets/1629853/19300878/ef6260dc-905c-11e6-9144-5c4deac0f801.png)

vs the working form: 

 ![capture d ecran de 2016-10-12 09-15-45](https://cloud.githubusercontent.com/assets/1629853/19300860/dda17a86-905c-11e6-9d54-222aa2d06c7e.png)

**Comment by mhugo** [comment]
Fixed in https://github.com/qwat/QWAT/commit/3b36a1c4dd5514ad6f80e121683eae40eb0f06d5

**Comment by haubourg** [comment]
Nice thanks!
