### ISSUE TITLE
Creer un groupe Board pour le suivi de projet

### ISSUE THREAD

**Issue by haubourg** [qwat/QWAT#153]
Le groupe Board sera sollicité pour les validations de décisions de pilotage de haut niveau sur le projet. 

Rôles : 
chaque organisation peut s'exprimer dans les tickets 

Animateur:  
@haubourg est chargé de vérifier que les organisations (actuellement SIGE, Lausanne, Morges et Pully) ont toutes validé la décision avant de la rendre opérationnelle. Le cas échéant, un consensus devra être trouvé avec une reformulation de la décision. Puis celle-ce fera l'objet d'une nouvelle validation.

Utilisation: 
Pour notifier / interpeller par mail le groupe projet du besoin d'une discussion stratégique il faut ajouter la référence @qwat/board dans les commentaires. 

Le groupe est ouvert. En cas de nécessité, les discussions privées se font en présentiel dans les réunions / atelier de pilotage

**Comment by haubourg** [comment]
@qwat/board test notification du groupe projet

**Comment by alexandrebosshard** [comment]
Salut Régis, pour la description de ton rôle d'animateur, je propose la phrase suivante:

@haubourg est chargé de vérifier que les organisations (actuellement SIGE, Lausanne, Morges et Pully) ont toutes validé la décision avant de la rendre opérationnelle. Le cas échéant, un consensus devra être trouvé avec une reformulation de la décision. Puis celle-ce fera l'objet d'une nouvelle validation.

**Comment by haubourg** [comment]
@alexandrebosshard  intégré!

**Comment by ponceta** [comment]
@haubourg board créé, utilisateurs informés, je pense que tu peux fermer le ticket ;)

**Comment by haubourg** [comment]
:)
