### ISSUE TITLE
Improve performances of current form lazy loading 

### ISSUE THREAD

**Issue by haubourg** [qwat/QWAT#154]
When opening a form with relation widgets, there is a significant loading time of all related child forms. 

Some users report that is even slower if form is in editing mode. 

For the record, there is some work in progress in that area (UX design):
 - http://osgeo-org.1560.x6.nabble.com/Visualisation-of-relations-td5289714.html

**Comment by dsavary** [comment]
Can we put the label Top priority for this issue ? 
Will this fixed for the QGIS version 2.xx LTR ? 
We cannot use the relations between layer in edit mode . The opening of the form is too slow for the users.

**Comment by haubourg** [comment]
@m-kuhn you told me you refactored things there. Can you tell us or point us to a PR to get what's the status here? Is there any chance the solution could be backported to 2.18 or is that a too heavy refactor?

**Comment by m-kuhn** [comment]
I started these improvements but never got around to finish it, but want to look at it again soon.

It will be hard to justify a backport, it's effectively a new implementation for the relation reference widget. This could possibly also done in a plugin implementation but it would be a considerable amount of work.

**Comment by haubourg** [comment]
@dsavary all we can do is attempt to optimize what you are loading and widget configurations it seems. 
Can you share your widget and relation configuration + screencast of the behavior?

**Comment by dsavary** [comment]
@haubourg  a demo GIF to show the problem : 
[https://share.oslandia.net/public/717c65](https://share.oslandia.net/public/717c65)
We use simply the relation widget in a form to show relation between two layers (for example, leak and pipe)
Do you want a project demo ?
I tested to make the relation with a layer without joints , I have the same problem.

**Comment by m-kuhn** [comment]
@dsavary does it work for you to check "show readonly line edit" the relation reference widget configuration?

**Comment by dsavary** [comment]
@m-kuhn Yes , it's better and faster with this options . Thanks.
But, if the "parent" layer is in "edit" mode (in my example, the layer "pipe" ) , it's always slow. 
I can add a second time the parent layer in my project without symbology as a list of values. The user cannot set this layer into edit mode, but can click on it to identify the relation. It's ok like that. :)

**Comment by m-kuhn** [comment]
I think "transaction mode" prevents from querying in parallel when the project is in edit mode.

Can you validate this hypothesis by disabling transaction mode on a slow layer? (I'd have an experimental idea how to fix this).

**Comment by dsavary** [comment]
If the "parent" layer (pipe) is in "edit" mode or/and if the "transaction mode" is active, the opening of the form (from the "child" layer) is very slow. In read only, it's ok and faster.

**Comment by m-kuhn** [comment]
If transaction mode is disabled, it is faster?

**Comment by dsavary** [comment]
yes

**Comment by haubourg** [comment]
> If transaction mode is disabled, it is faster?
Are you talking about transaction group mode (in project properties) or something else?

**Comment by m-kuhn** [comment]
yep, transaction group

**Comment by dsavary** [comment]
it's important that the layer is in **READ-ONLY** mode. the option "transaction group" can be disable or not.

**Comment by haubourg** [comment]
After some issues with another project, we found in QGIS2 that relation reference widget in some cases loads more than three times the related table. 
A first fix was made here https://github.com/qgis/QGIS/pull/5677 to avoid the two unnecessary fetches from other project fundings. However, we still hit blocking issues in some cases with recursive infinite queries, individual fetches on each target layer's id or setting NULL value that doesn't update.
So I'm afraid we are on a big task here.

**Comment by m-kuhn** [comment]
Any feedback on the QGIS 3 situation? qgis/QGIS#5677 pretty much is a port of a fix I did for QGIS 3, but there's much more in there.

**Comment by haubourg** [comment]
@m-kuhn Sorry for not being able to know where code lines come from.  
In short 2.X implementation suffers from some bugs we are working on, but one sure thing is that it won't scale because form loading in edit mode will fetch the referenced whole layer to populate the edit widget (except for the option "use readonly line instead of comobox" - but in some cases, it seems data is fetched anyway). 
So the more lines in the reference table, the slower opening the form is. 

@m-kuhn If I get it well, lazy loading in QGIS 3 will solve partly things:
- readonly in classic mode will use another thread. This is the brutal force option, but doesn't solve the fact it is not scaling well
- transaction groups will block multithread (I couldn't check that yet), so this won't be much better.

Is there any path to have a scalable solution, which could be leaner like : 
 - only pre-load target features in current extent (for map layers)
 - only load necessary fields (id, display expression output). Is geometry used here ? It is already fetched for map display AND for snapping index) It would be nice the relation reference widget doesn't query it. 

Thanks for your lights on that really complex area and helping us in creating atomic actions easier to adress.

**Comment by m-kuhn** [comment]
> transaction groups will block multithread (I couldn't check that yet), so this won't be much better.

It will still be multithreaded. What happens is: background thread will be blocked, while the UI is already being loaded and shown. Values in the relation reference widgets will be added to the form when loaded.

> only pre-load target features in current extent (for map layers)

the new system will permit to add this, I'll be happy to implement this solution. It will not be more performant but a nice usability fix.

> only load necessary fields (id, display expression output). Is geometry used here ? It is already fetched for map display AND for snapping index) It would be nice the relation reference widget doesn't query it.

that's implemented already

**Comment by haubourg** [comment]
Thanks for the explanations ! I'll test QGIS3 more intensively then.

**Comment by haubourg** [comment]
for QGIS2 @pblottiere just issued a PR that reduces a lot number of queries sent to the databases and avoids the relation widget to do unnecessary queries to the DB when the embedded relation reference widgets have the options "readonly" and "point on the map". 
It still does not solve the cases for non geographic tables, but this works !!
See https://github.com/qgis/QGIS/pull/5783

**Comment by dsavary** [comment]
With QGIS, we start to use more and more relations "parent-enfant" between some tables in DB. 
The relation is not only between spatials tables, but also between "non spatial" tables
When we create a relation between tables in QGIS project and use the "reference value widget" in the form settings, there are frequently problems of performance to load the "attributes table" or "feature form". It becomes a priority for Lausanne to fix these bugs/problems and we works regularly with lots of data.
Are some developments planned to solve these problems ? for QGIS 3.0 and QGIS 2.18 ?
Some remarks : 

- The loading perfomance are fast only with the options "readonly" and "point on the map".
As @haubourg said, it's a problem for non geographic tables... 

- With the option "readonly", you cannot modify the value in edit mode (Does it not exist a mode "completion" as the widget "valeur relationnelle" ? )
![valeur_relationnelle_completion](https://user-images.githubusercontent.com/6229296/38626232-a8fe3c90-3d9b-11e8-97f9-12f7b4aa9c1b.PNG)

- the options "permettre l'ajout de nouvelles entités" to add a new feature works well but it would be better if it propose to the user to add a geometry for spatial layer and not a feature without geometry...

**Comment by ponceta** [comment]
QGIS 3 has considerably enhanced forms loading. This can be closed since.
