### ISSUE TITLE
[Website] History page

### ISSUE THREAD

**Issue by ponceta** [qwat/QWAT#157]
Hi, 

Several months ago, it was discussed that @tudorbarascu should be mentionned at least on the history page http://0e925d873b.testurl.ws/history/ and as one of the main contributors for the project.

It could be great to update these informations.

And there's a technical failure on the website since clicking on the history menu should not redirect to http://0e925d873b.testurl.ws/history/ but http://qwat.org/history/

A small map of QWAT users could be great to add to this page! 

Grey text is a bit light for reading don't you think? @qwat/board

**Comment by sylvainbeo** [comment]
Hi,

Urls just have been fixed..

**Comment by ponceta** [comment]
@sylvainbeo Merci! ;)
