### ISSUE TITLE
[Website] Navigation

### ISSUE THREAD

**Issue by ponceta** [qwat/QWAT#159]
Enhancements proposals for qwat website @qwat/board, critics and thoughts are welcome!

The home page of qwat website is shiny, but its navigation is misleading the user:
(at least on desktop since on mobile there is no arrow and no scrolling needed)

The arrow 

![image](https://cloud.githubusercontent.com/assets/8614223/20514057/30fd2f48-b08a-11e6-81ba-ce50cdc84d47.png)

is misleading the user to scroll down instead of clicking on the title to get into what's really about.

And once scrolled down to this amazing news : 

![image](https://cloud.githubusercontent.com/assets/8614223/20514103/6ee33082-b08a-11e6-86cb-a7edb932571d.png)

You have to scroll back up to get to the menu, otherwise you will get to the same news page.

![image](https://cloud.githubusercontent.com/assets/8614223/20514128/91359ab2-b08a-11e6-97c2-d68655c5b442.png)

I suggest to replace the 1st news by the "about" section which tells us more about QWAT.

The menu button on the "about" page is really small and it should be more visible. (IMHO)

The "what it looks like" printscreen could have a better resolution. (IMHO) and should be actualized once the qwat 2.0.0 model is released and the project is adapted.

**Comment by sylvainbeo** [comment]
Needs validations.

**Comment by haubourg** [comment]
closing since a full rework of the website is planned in 2018
