### ISSUE TITLE
Demo data improvement

### ISSUE THREAD

**Issue by 3nids** [qwat/QWAT#160]
Things to be improved

* [ ] data should be migrated automatically with model updates. See how QGEP does for instance (Travis automatically run the migration process). See #98 
* [x] data demo dump must be upgraded to latest version manually. All data tables should be filled and with anonymous data.

**Comment by haubourg** [comment]
@sylvainbeo  could you evaluate how much time that would require?

**Comment by sylvainbeo** [comment]
Are we talking about automatically produce a new demo dataset when the model evolve, or just check if the model's evolution can be applied on the current demo dataset without any errors ?

**Comment by 3nids** [comment]
doing automatically the process. I know QGEP is doing it automatically via Travis. @m-kuhn may you shortly explain how it works (what repo is doing what and how)?

**Comment by m-kuhn** [comment]
Repo [datamodel](https://github.com/QGEP/datamodel) contains only the schema + static data (value lists). There are some pg sanity checks in place, if they succeed on master, two things happen:

 * a release of the datamodel (empty) https://github.com/QGEP/datamodel/releases
 * a pull request against the main repo is opened

In the [main repo](https://github.com/QGEP/QGEP/pulls), some real data is migrated and some integration tests are done. On new commits on master (given tests succeed) the demodata is updated: pg dump with demodata + qgis project file.

**Comment by haubourg** [comment]
@sylvainbeo could you estimate how much time is required to do that in QWAT?

**Comment by haubourg** [comment]
I created a new and more complete demo dataset in qwat-data-sample repository. 
@sylvainbeo this is I think a good candidate to use in the testing and release process.

**Comment by haubourg** [comment]
@3nids a new data sample was released as asked at the general meeting 15/03. It has cleaned folios, all remark, repair and description fields have been manually cleaned to keep relevant demo data but with no private information in it (adress, names, company names).

**Comment by sylvainbeo** [comment]
@3nids @haubourg Work in progress. See :
https://github.com/qwat/qwat-data-model/blob/upgrade/update/verify_upgrade_db.sh

The process is doing the following 
https://travis-ci.org/qwat/qwat-data-model/builds/212161058
Watch at line 2262

Now, i have to dump the database, and update the demo-data-sample git.
By the way, do you now if i can do this via travis  ? (i guess so, but for the moment, i get the git content via HTTPS, so i'm not sure i can push the DUMP easily).

I need also to read the backup file dynamically.

@haubourg  Can you give me the pg_dump command you launched for your latest DUMP  ?

Thanks.

**Comment by m-kuhn** [comment]
Hey @sylvainbeo 

For reference, that's how we release automatically from travis

https://github.com/QGEP/datamodel/blob/master/scripts/release_db_template.py

**Comment by sylvainbeo** [comment]
@m-kuhn Thanks. Cool, i think i'm going to reuse that.

**Comment by m-kuhn** [comment]
Cool, you possibly want to work on git tags to only release consciously.

**Comment by haubourg** [comment]
@sylvainbeo I dumped the data only dump using 
```
/usr/bin/pg_dump --host localhost --port 5432 --username "postgres" --no-password  --format custom --blobs --section data --verbose --file "/home/regis/OSLANDIA/projets_locaux/QWAT/qwat-data-sample/qwat_v1.2.1_data_only_sample.backup" --schema "qwat_dr" --schema "qwat_od" "qwat"
```

**Comment by sylvainbeo** [comment]
Almost there. 
I need to adapt @m-kuhn script for Qwat. In our case, we have to authent to github before we can push the DUMP, because it is store in another repository

**Comment by m-kuhn** [comment]
@sylvainbeo we also needed to do this with https://github.com/QGEP/datamodel/blob/master/scripts/release_db_template.py#L18-L22

The upload is not pushed to git, but to the releases page of the repository.

**Comment by sylvainbeo** [comment]
@m-kuhn And where do you get the token from  ?

**Comment by m-kuhn** [comment]
I think it was somewhere [around here](https://github.com/settings/tokens) or [https://github.com/settings/developers](here).

**Comment by sylvainbeo** [comment]
@m-kuhn Mmm, but this will be a personnal token. I don't get it.

**Comment by m-kuhn** [comment]
I think we made a new github user @qgep-bot for this purpose. It's possible that there are other ways (more organization oriented).

**Comment by sylvainbeo** [comment]
@3nids @haubourg  What do you think. We create a special github user for qwat ? If so. Who will be the owner  ?

**Comment by sylvainbeo** [comment]
@3nids @haubourg up. WHo should be the owner of this github user ?

**Comment by 3nids** [comment]
I don't really mind.
A solution could be to use some address like admin@qwat.org.
Anyway, this could be readapted any time.
If you want I can create it, otherwise feel free to do so.

**Comment by sylvainbeo** [comment]
@3nids yes please. We have to ask Carlos to create the admin@qwat.org so, he is the one who own the domain

**Comment by qwat-admin** [comment]
sorry for the delay

usr created, credentials under share plaftorm: /technique/github-qwat-admin.txt

**Comment by sylvainbeo** [comment]
What email adresse did u use ?

**Comment by 3nids** [comment]
mine @sige.ch we can change it whenever needed

**Comment by sylvainbeo** [comment]
Ok i've finished the whole process. 

@3nids @haubourg @m-kuhn  could you have a quick look at the verify_upgrade_db.sh ( https://github.com/qwat/qwat-data-model/blob/upgrade/update/verify_upgrade_db.sh )  before in launch the PR  ?

@m-kuhn I did not used a python script. All the process is made in the shell script.

Thanks.

**Comment by ponceta** [comment]
@haubourg @sylvainbeo where are we in this issue?
 Did you :
 - [ ] asked @carlos-gil for admin@qwat.org
 - [ ] asked @github for token issue?
 - [ ] see with @m-kuhn and @marioba on how it works with qgep demo data?

As we are currently fixing PUM, that would be great to fix this so that we could focus on QWAT evolutions.

**Comment by sylvainbeo** [comment]
Hi,

As PUM is now existing...what is the future of the current migration scripts ? Should we spend some more time to fix it, if we replace it with PUM  ?

**Comment by ponceta** [comment]
@sylvainbeo next @qwat/qwat-psc will be focused on PUM on 18.10.2017. It would be great to discuss and assess this too. It will be online meeting 10:00-12:00.

**Comment by haubourg** [comment]
We discussed that during the PSC. It was decided to bet on PUM only and avoid duplicated efforts

**Comment by haubourg** [comment]
almost done in deploy scripts along with PUM in 1.3.0. Latest test today showed release was done automatically bu upload of dump failed (no clear logs)

**Comment by m-kuhn** [comment]
fixed as of 2 hours ago

**Comment by haubourg** [comment]
Dumps appear to be empty. @m-kuhn @sylvainbeo we probably missed the restore step with demo data in 1.3.0. 
what would be the right process?

1- manually replace existing dumps with  demo data dumps in 1.3.0. 
2- restore the previous data only demo before PUM applies the delta
3- dump as today

**Comment by m-kuhn** [comment]
I might be missing something, I haven't looked into the pum process itself a lot.
I think it would make sense to restore a demo data dump before and send it through the deltas, that will also increase chances to detect broken deltas.

**Comment by haubourg** [comment]
Exactly. I think we should do that around line 44 in travis.yml. 

We need in fact:
1- get the previous tag meeting the x.x.x version template (just now the previous tag is "test"), so a loop with something like `git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`

2- wget the corresponding data-only dump (custom format with .backup extension)

3- restore that line 49 after initial qwat_prod creation
`  - pg_restore --dbname"service=qwat_prod" --data-only --disable-triggers  --no-owner mylatestdataonlydump.backup
` 

@sylvainbeo @m-kuhn @marioba. Anyone available to fix that and close the migration topic ?

**Comment by m-kuhn** [comment]
Can't we just restore the first-ever dump and run that through all the deltas?

**Comment by haubourg** [comment]
That would be nice, but the first ever correct data demo dump has been done in 1.2.6. I don't know how to downgrade delta from there back to 1.0.0

**Comment by m-kuhn** [comment]
Whichever it is, it's just easier to implement if it's a stable version.

**Comment by haubourg** [comment]
In PR #213, I propose to run travis only from 1.2.1 full dump with demo data. @m-kuhn, does that look good to you?
