### ISSUE TITLE
Project Management proposal - use Huboard for Github

### ISSUE THREAD

**Issue by haubourg** [qwat/QWAT#162]
Hi @qwat/board, 
I just tested some Github tools to improve ticket management efficicency and readability since we have more than 66 tickets open, dispatched over 2 repositories . 
This tool allows to handle tickets in a AGILE / whiteboard + post-it way for milestones AND work status. 
You can check QWAT status here:
https://huboard.com/qwat/QWAT/#/ 

I'm still working on linking the data-model repo to the same dashboard. 

This is an experimentation, please tell me if this does not seem accurate and we can rollback all that. 

Régis

**Comment by ponceta** [comment]
@haubourg I've discovered gitter 5 min ago, is there a gitter channel for qwat? seems pretty nice to communicate.

For Huboard, IMHO it's yours to decide wether your tool will be since the issues management is pretty well under your management now?

**Comment by haubourg** [comment]
yes please check https://gitter.im/qwat heavily used by Sylvain and Denis. 
Concerning Huboard, I wanted to share because other owners have rights on the repo and could play with tags. So it's better that everyone knows about it. Since it's a first try of the tool, it'ss always interesting to know if others have been playing with it also.  
Cheers

**Comment by ponceta** [comment]
Heavily is the word. Ty.
Concerning Huboard, I like the tool, it just need a very good labelling of issues.

**Comment by haubourg** [comment]
@ponceta with huboard, you don't need to handle labels, just drag issues in columns and labels are updated.

**Comment by ponceta** [comment]
Is it possible to define a "close" column to close issues after they're done and avoid having these kind of tickets which should have been closed a while ago ?

**Comment by ponceta** [comment]
https://github.com/qwat/QWAT/issues?q=is%3Aopen+is%3Aissue+label%3A%224+-+Done%22

(labeled as Done tickets)

**Comment by haubourg** [comment]
"Closed" is already a github tag, and huboard is somewhat fixed to 5 columns. Anyway the columns can be expanded or folded this way, and this is persistent:
![image](https://cloud.githubusercontent.com/assets/1629853/23696612/a70fca30-03e4-11e7-97c0-a0c01a2e20d9.png)
Another point is that keeping a view of done task is helpful for logging (at least to me)
