### ISSUE TITLE
Add soft constraints in forms

### ISSUE THREAD

**Issue by haubourg** [qwat/QWAT#165]
The idea is to have constraints allowing warning, but not blocking commits for forms

**Comment by haubourg** [comment]
asked on technical meeting 18/01/2017

**Comment by haubourg** [comment]
Seems done in master QGIS 3 with the "enforce constraint" checkboxes

![image](https://cloud.githubusercontent.com/assets/1629853/22433280/234df994-e718-11e6-97b7-d58b31b906a0.png)

**Comment by haubourg** [comment]
@ponceta @m-kuhn @dsavary
Do you confirm this is what we talked about?

**Comment by m-kuhn** [comment]
Yes

**Comment by dsavary** [comment]
Yes
