### ISSUE TITLE
Add a webpage to site showing all new features funded by QWAT project

### ISSUE THREAD

**Issue by haubourg** [qwat/QWAT#168]
List features, and versions when it landed in the code.

**Comment by haubourg** [comment]
- Default Z value for 3 data [in QGIS 3]
- Refactor node tool to clic-clic instead of drag and drop + usage of advanced digitizing constraints for existing features (was before only for new features)  [in QGIS 3]
- Fixes snapping refresh issue when triggers change geometry in DB after commit (REF ? VERSION .?)
- New plugin History audit trigger to store edits in DB, find them in a nice interface and replay old edits 
- Fixes 3d inconsistency for editing tools on z values  [in QGIS 3] 
- Adds 3d creation option for new datasets (gpkg, spatialite, shp, memory layer..) [in QGIS 3]
- Constraints in forms extensions to any expression  [in QGIS 2.16]
- Magnifier tool in MapCanvas  [in QGIS 2.16]
- CAD editing improvements 
- Advanced digitizing panel bringing geometric constraints when drawing (distance, angle, parallel, perpendicular) (Version?)
- Snapping options refactoring from dock to toolbar  [in QGIS 3]

**Comment by haubourg** [comment]
@3nids could you enrich that so that we can push it to the website? I think there are a lot of things in your [commit history](https://github.com/qgis/QGIS/search?o=asc&q=3nids&s=committer-date&type=Commits&utf8=%E2%9C%93) :)

**Comment by 3nids** [comment]
from my self:

- new snapping widget (Q3)
- drag'n'drop designer (Matthias finished the work)
- new attachment widget (Q3)
- copy-move feature map tool (Q3)
- identify map tool menu (1fb524f1195251833edef4637a619cb76ec37ead)
- map layer and field comboboxes
- custom widgets infrastructure for Qt Designer
- date/time edit widget refactoring
- relation reference widget: map picker tool
- user input widget (for map tools: e.g. rotation)
- map magnifier (in collaboration with Oslandia)
- (spelling error detection)
- (python bindings automatic generator aka sipify)
- and a few fixes ;)

sponsored

- atlas composer
- legend refactoring
- snapping refactoring 
- multi-threading
- 1:n relations
- n:m relations
