### ISSUE TITLE
QGIS server problem regarding the qwat.qgs

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/qWat#17]
As in the qwat project we're using styling that is based on joined table column values, I wanted to ask you if you're using QGIS server for presenting your project as I encountered [this issue](http://hub.qgis.org/issues/12307) and if you know how to bypass this.
Thank you.

**Comment by 3nids** [comment]
No, I'm not using the server to publish map.
You might want to get some feedback from Martin Dobias for this. I will ask him.

**Comment by yjacolin** [comment]
Hello

I confirmed this wrong behaviour with QGIS Server 2.6 specially with the
"conduite" layer (sorry i dont know the english name).

QGIS 2.8 not tested.

Y.

**Comment by tudorbarascu** [comment]
Thanks a lot, I also just confirmed the issue with QGIS Server 2.4, ubuntu 12.04
Should I close down the issue as this doesn't touch your use case?
A great morning to you!

**Comment by 3nids** [comment]
Let it open until I have feedback from Martin.
We will have a rough idea about the effort to solve this.

**Comment by yjacolin** [comment]
Ping @xmenetrey ;)

**Comment by 3nids** [comment]
Martin's reply:

>Hi Denis
>
>from a quick look I can't really tell - there were few join-related commits on the road to 2.8, both in  server and core libs. And from the report it is not clear if that is a regression from 2.6 or a longer term problem with 2+ joined layers.
>
>I'm just wondering... are you running QGIS server for anything?
>
>In my humble opinion the way how QGIS server works with projects is completely wrong... instead of using QgsProject it parses a lot of stuff manually from XML, so I am not surprised that things get broken in the server code every now and then...
>
>Cheers
>Martin

Hence, I cannot offer to solve this via Martin under the support contract I have with him. Sorry for that.

**Comment by tudorbarascu** [comment]
The problem is certainly from 2.4 on (probably for all 2+ versions).
As I didn't had more than one joined layer until now it slipped through although we're using QGIS server for some time.
Thanks a lot anyway Denis,
All the best

**Comment by yjacolin** [comment]
ping @xaviermenetrey

**Comment by xaviermenetrey** [comment]
Hi, 

We encountred the same issue with qgis server 2.6.

All layer's settings (styles, labels, and so on) based on joined attributes were broken.

I created some views and replaced the "broken" layers.

It solved the problem.

**Comment by tudorbarascu** [comment]
Yes, views are a walk around but an expensive one when you have complex project and the layer needs to be editable (rules on views etc.). It seems Marco [has fixed the issue](https://github.com/qgis/QGIS/commit/b83b59dc77be55ea4424a0611edcd7f3e9a05c44)

**Comment by tudorbarascu** [comment]
I just tested and indeed the issue is solved in master. Shouldn't it also be pushed to 2.8.2?
