### ISSUE TITLE
Installation part value list has empty values 

### ISSUE THREAD

**Issue by haubourg** [qwat/QWAT#170]
See:
![uploads/1b2cf4d3-b2bd-4b10-9d35-fc291630c842/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1b2cf4d3-b2bd-4b10-9d35-fc291630c842%2Fblob)

This leads to troubles in UI forms.

**Comment by 3nids** [comment]
9201 et 9205 sont des doublons.
pour le reste, on peut ajouter les traductions

**Comment by haubourg** [comment]
@tudor, you have two different names (dop and capăt reţea ), do you consider them as duplicates?			
if not, can you provide the french translations? 
if they are true duplicates, we'll have to handle data migration in the new version. Which one of 9201 - 9205  should remain?

**Comment by tudorbarascu** [comment]
@haubourg For us, a network end can have one of the possibilities: valve, hydrant and **end fitting**.
We differentiate the **end fitting** in two, for plastic pipes (**dop** in romanian - translating as **bouchon** in french - fitted on pipes through **heat sealing** - **thermoscellage**) and for steel pipes (blind - no translation, fitted on pipes through **welding** - **soudage**).
So, at the first glance, **bouchon** is one of the two subtypes for **end fitting**.

So, is **bouchon** the term you use for all end fittings without the need to differentiate?
If so, then indeed they are duplicates.
If not, do we need to differentiate?

**Comment by lbartoletti** [comment]
https://github.com/qwat/qwat-data-model/pull/247

**Comment by lbartoletti** [comment]
Version 1.3.3 https://github.com/qwat/qwat-data-model/issues/250
