### ISSUE TITLE
python init script does not seem to be loaded when switching row in attribute table

### ISSUE THREAD

**Issue by haubourg** [qwat/QWAT#180]
The issue has been raised twice. Python script is sometimes not loaded when changing form in attribute table. 

My first attempts to make it reproducible fail. Let's try to focus it together before raising it in qgis bug tracker.

**Comment by haubourg** [comment]
Here is an archive with a simple project file + gpkg dataset. 
[BUG_INIT_FORM_NOT_LOADED.zip](https://github.com/qwat/QWAT/files/913862/BUG_INIT_FORM_NOT_LOADED.zip)

**Comment by haubourg** [comment]
@sylvainbeo @dsavary Hi, Could you check with the dataset above if you spot a case where the init logic is not satisfied? 
(opening the form should just open a message box)
Maybe it's datasource dependent?

**Comment by sylvainbeo** [comment]
@haubourg Indeed with your project it seems to work fine.

**Comment by haubourg** [comment]
Closing it, we can't reproduce the issue

**Comment by dsavary** [comment]
Sorry for my late response.
I cannot reproduce the problem. The init script load well when we open a feature form or when switching row in attribute table. Everything is ok.
The only small problem that I had seen is when we open a form of a new feature. The init script is load once when the form open and once again after we valid the form. Perhaps, this behavior is normal...
