### ISSUE TITLE
QWAT Server / Client specs

### ISSUE THREAD

**Issue by ponceta** [qwat/QWAT#183]
As in https://github.com/QGEP/QGEP/issues/308

I ask here what would be good specs for client and server for QWAT.

I'm talking about server recommanded CPU and RAM in particular but of course other specs could be add like PG version and so on (which is in the doc)

Having some rendering latency issues on QGEP, this will probably impact my QWAT Users (since both are working on the same server)

Having some DB specialists advices could be great here @sylvainbeo @vpicavet.

**Comment by tudorbarascu** [comment]
@ponceta For db, take a look at https://momjian.us/main/writings/pgsql/hw_selection.pdf

**Comment by haubourg** [comment]
@ponceta Did you find improvements applying what's been proposed in QGEP's thread or do you need us to make dedicated tuning work of your server's and global architecture ?

**Comment by ponceta** [comment]
I see all elements I needed in https://github.com/QGEP/QGEP/issues/308

@tudorbarascu thanks for the link.

@haubourg Actually QWAT runs pretty well on our server, (Processors and RAM are pretty large in terms of what is really used.) 

I know understand Specs are organization size dependant for these aspects.

**Comment by tudorbarascu** [comment]
@ponceta Can this be closed?

**Comment by ponceta** [comment]
Yes!
