### ISSUE TITLE
Add status for pipes ?

### ISSUE THREAD

**Issue by haubourg** [qwat/QWAT#184]
Hi, question raised by varrieta.
GeoCom ESRI figures a status field to describe if a pipe is in good, poor, or bad shape. 

According to Denis, as it is rare to have real inspections on water pipes, information is rarely available. It is in general estimated using the age, materials and leaks frequency. 

I couln't find that information in SIA or SIRE format. 

So is anyone interested in handling such a field?

**Comment by varrieta** [comment]
I agree with Denis and it's not a problem for us not to maintain this field.

**Comment by haubourg** [comment]
Ok then, I close the issue. Please reopen if necessary
