### ISSUE TITLE
Move selection to the top QGIS 2.18.X (tracking on QGIS)

### ISSUE THREAD

**Issue by ponceta** [qwat/QWAT#187]
Since QGIS 2.18.X, Move selection to the top is broken.

QGIS Tracking Issue
https://issues.qgis.org/issues/15803

Fix Tracking
https://github.com/qgis/QGIS/pull/4306

**Comment by haubourg** [comment]
It happens only when playing with sorting. Luigi seems to be narrowing down the issue (and could squash three bugs in the same fix). Let's check again in latest release-dev or 2.18.8 when the fix is applied

**Comment by ponceta** [comment]
I get it every time I select from map on QGIS 2.18 :

![](http://i.imgur.com/rqCjq8w.gif)

**Comment by haubourg** [comment]
The issue has been identified at the hackfest here:
http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-attributetable-15803-quot-Sort-on-Top-quot-regression-or-feature-td5319850.html

**Comment by haubourg** [comment]
fixed in master and 2.18
