### ISSUE TITLE
[Website] enable www.qwat.org redirection.

### ISSUE THREAD

**Issue by ponceta** [qwat/QWAT#188]
www.qwat.org ends on :

![image](https://cloud.githubusercontent.com/assets/8614223/25801730/4253c0f2-33ef-11e7-85a0-e3a5998b5bc2.png)

**Comment by sylvainbeo** [comment]
En cours de redirection.

**Comment by haubourg** [comment]
aujourd'hui, on a ça:
```
Error 404 Vhost unknown.

Vhost unknown.

Varnish L7 server
```

**Comment by ponceta** [comment]
![image](https://user-images.githubusercontent.com/8614223/26837071-c291ae2e-4adc-11e7-9dbf-413d321da5d4.png)

**Comment by haubourg** [comment]
Fixed, thanks for raising the issue!
