### ISSUE TITLE
Relation widget reference fails if filter value contains a quote

### ISSUE THREAD

**Issue by dsavary** [qwat/QWAT#191]
QGIS bug report : [https://issues.qgis.org/issues/16399](https://issues.qgis.org/issues/16399)
Moderate priority

**Comment by haubourg** [comment]
Work planned for the end of june/ early july

**Comment by pblottiere** [comment]
I launched a PR about this issue : https://github.com/qgis/QGIS/pull/4810

**Comment by pblottiere** [comment]
PR is merged.

Now I have to work on backporting.

**Comment by dsavary** [comment]
Thanks !

**Comment by pblottiere** [comment]
PR for backporting has been merged : https://github.com/qgis/QGIS/pull/4833

**Comment by haubourg** [comment]
Merciii @pblottiere !!
@dsavary can you test that with nightlies of the release, starting from tomorrow of course..

**Comment by dsavary** [comment]
@haubourg  Before test the "new" reference value widget, I wait for the resolution of the issue #186 .

**Comment by dsavary** [comment]
Tested with QGIS 2.18.11 nightly , it's Ok . the chain filter can take a value with quote. 
Thanks

**Comment by pblottiere** [comment]
@haubourg I think this issue can be closed now.
