### ISSUE TITLE
 switching between layer styles breaks relation widget

### ISSUE THREAD

**Issue by dsavary** [qwat/QWAT#192]
QGIS bug report : [https://issues.qgis.org/issues/16100](https://issues.qgis.org/issues/16100)
Moderate priority for Lausanne

GIF for the demo :
[https://share.oslandia.net/public/6c8aed](https://share.oslandia.net/public/6c8aed)

**Comment by haubourg** [comment]
@pblottiere issue to inspect when you start the form bug fix tasks

**Comment by pblottiere** [comment]
I created a PR about this issue : https://github.com/qgis/QGIS/pull/4822

**Comment by haubourg** [comment]
Ok thanks, when merge, we'll need backports 2.18 branch for those forms issues

**Comment by pblottiere** [comment]
PR is merged. 

Now I have to work on backporting.

**Comment by pblottiere** [comment]
Thank you @m-kuhn for having made the backport!

I think this issue may be closed.

**Comment by haubourg** [comment]
l mark it done, let's close only after backport and testing by @dsavary

**Comment by dsavary** [comment]
good news ! Thanks for the work ! in which version of QGIS can I test this ? 2.18.11 ?

**Comment by m-kuhn** [comment]
Or an upcoming 2.18 nightly (available via osgeo4w)

**Comment by dsavary** [comment]
Tested with QGIS 2.18.12. It works well.
Thanks

**Comment by pblottiere** [comment]
@haubourg I think this issue can be closed now.
