### ISSUE TITLE
scroll bar locked when opening a form in read-only mode

### ISSUE THREAD

**Issue by dsavary** [qwat/QWAT#194]
For a multiple selection attribute, we cannot see the complete list because de scroll bar is locked.
It's only possible to see the values by switching into edit mode. 

See the Demo GIF  [https://share.oslandia.net/public/b40a2c](https://share.oslandia.net/public/b40a2c)

**Comment by haubourg** [comment]
raised upstream https://issues.qgis.org/issues/16654

**Comment by haubourg** [comment]
@pblottiere can you evaluate that issue when you'll start the bugfix work on forms?

**Comment by ponceta** [comment]
If we follow the other tools logic, it should only display selected values when not in edit mode, thoughts?

**Comment by pblottiere** [comment]
I found a way to keep the scroll bar activated even if we are not in edit mode.

And @dsavary, what do you think about suggestion of @ponceta?

**Comment by dsavary** [comment]
@pblottiere It will be a good idea to display only the selected values or to put on the top of the list the selected values. But, now we cannot do this with the current tool/options widget or perhaps I don't know how we can do this.

**Comment by pblottiere** [comment]
A PR is proposed to keep the scrollbar activated even in read only mode : https://github.com/qgis/QGIS/pull/4905

**Comment by pblottiere** [comment]
PR mergée.

Je prépare une PR pour le backport.

**Comment by pblottiere** [comment]
PR for backport : https://github.com/qgis/QGIS/pull/4925

**Comment by pblottiere** [comment]
Backport has been merged

**Comment by dsavary** [comment]
Tested with QGIS 2.18.11 nightly , it's Ok .

**Comment by pblottiere** [comment]
@haubourg I think this issue can be closed now.
