### ISSUE TITLE
Question : Importing views as QGIS layers

### ISSUE THREAD

**Issue by ponceta** [qwat/QWAT#197]
Hi, 

Is it possible to define the id in the views to load these more easily than having to select id from entity everytime when loading a view?

![image](https://user-images.githubusercontent.com/8614223/27168546-6e1de13e-51a6-11e7-9248-dc7afd1b4448.png)

**Comment by ponceta** [comment]
AS I understand it, views in postgres can't have PRIMARY KEY (https://stackoverflow.com/questions/11667508/how-to-add-primary-key-to-view)

(Oracle has)

It is an issue for Open/libreoffice editing in postgres too.

It could be an issue for ETL editing like FME probably.

**Comment by ponceta** [comment]
@vpicavet any hope this could change in the next years?

**Comment by tudorbarascu** [comment]
@ponceta I think a convention to specify the unique id in the table comment could work. Don't think anything like that is implemented though.

**Comment by haubourg** [comment]
Hi, in fact if you use the browser panel to load, QGIS will try to find alone the most suitable unique id field.

**Comment by ponceta** [comment]
Why having different behaviours? Data source manager should have default suggest the most suitable id field and propose to the user to change it if necessary?

Thoughts?

**Comment by ponceta** [comment]
And this valid for standard layers too (show the selected column chosen as unique id)

**Comment by haubourg** [comment]
Well, UX consistency is an issue in QGIS. Another explanation can be that the browser tab has its own thread to scan datasources and do not freeze the main thread, which is not the case for the classical DB dialog. 
That would be worth opening a feature request in QGIS for sure, I had the same reaction a few weeks ago.

**Comment by ponceta** [comment]
This has been fixed on QGIS 3.4.X QWAT views can be loaded in 1 click for views which have id as first attribute.

Exceptions are 

- qwat_od.vw_qwat_network_element : because there's a select case on qwat_od.element_type
- qwat_od.vw_qwat_node : because there's a select case on qwat_od.node_type
- qwat_od.vw_search_view : because there's a select case on 'Ouvrages'::text AS layer_name
