### ISSUE TITLE
QGIS : Zooming to an entity with no geometry results in a freeze for navigation interface

### ISSUE THREAD

**Issue by ponceta** [qwat/QWAT#198]
If an entity has no proper geometry, zoom to this selected feature will lock the canvas at current state with no error message.

![zoom_to_selection_no_geom](https://user-images.githubusercontent.com/8614223/27173997-ca3714ea-51ba-11e7-9e80-0cc9312ad895.gif)

![image](https://user-images.githubusercontent.com/8614223/27174085-26ce6ef6-51bb-11e7-8a48-270b337e7f22.png)

**Comment by ponceta** [comment]
Workaround to unlock, select a feature with proper geom and zoom to this feature.

**Comment by tudorbarascu** [comment]
Should have been fixed in https://github.com/qgis/QGIS/commit/eabdb656a2f152c6c04a9df8d533e8b9c3884199

Guess it regressed.

**Comment by 3nids** [comment]
was fixing it....
I am taking care of zoomToSelected

**Comment by 3nids** [comment]
oh and it's 2_16 only
taking care of master (and 2_18?)

**Comment by 3nids** [comment]
now fixed in master and 2_18

**Comment by ponceta** [comment]
Ty @3nids
