### ISSUE TITLE
Add to the qgs project the ouvrages_polygon layer

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/QWAT#202]
Hi,

On my localized project we're using another layer named  **ouvrages_polygon** (translated) which is the same as **ouvrages** except it points to the polygon_geometry.

I would like to at this to our baseline project.

Do others use the polygon_geometry?
Opinions?

**Comment by haubourg** [comment]
As long as it shows a QWAT hidden capability, I'm +1 in exposing it.  
We need to add geometries examples to the data sample dumps. Could you add here some realistic screenshots so that I know what kind of drawing can be expected and push some in the dataset ?

@3nids do you use that geometry?

**Comment by tudorbarascu** [comment]
For a water-flow meter installation (chambre debitmetre), you can describe it as a point but you can also describe the installation boundaries.

See a QWC2 gif where you can see the installation chamber, the point representing the flow-meter and also the cover (couvercle) in the bottom right corner of the polygon.
 
![demo](https://user-images.githubusercontent.com/3179646/27873960-80c8883c-61b6-11e7-8a45-cbeaa0208e9a.gif)

**Comment by haubourg** [comment]
@tudorbarascu @3nids while on it, I see no trigger to initialize the geom_polygon of installation when creating a new element. 
How do you handle the creation of a geometry on an existing point with NULL geometry? 
I tried the "add part" edit tool with no result and failures inside the DB logs related to audit trigger and NULL hstore (v 1.2.6). 

Should we add a layer action to initialize a polygon geometry (making a square buffer of 5 m for instance) and then let the user modify it?

**Comment by tudorbarascu** [comment]
We always add a point installation before making use of the addpart tool and create the polygon geometry.

I would prefer not to automatically generate the polygon as I wouldn't want map users forgetting on how the polygon was created and taking it for real.
We could mitigate this with styling (e.g. generated polygons with that exact geometry would be in a specific named group etc.). However, maybe somebody forgets this database side and starts doing some reports based on those.

I think adding a "Describe installation polygon" action that would start the **Addpart** tool on that exact feature would improve the work-flow quite a bit.

**Comment by tudorbarascu** [comment]
@haubourg Whoops, that's what you proposed. Yes.. that's what we want. Doh...

**Comment by tudorbarascu** [comment]
@haubourg cool. 
``then something is broken in my install``
I just tested with the latest data model and it works.

**Comment by ponceta** [comment]
This is used in Pully as well, should be in the demo project.
