### ISSUE TITLE
Issue with launching the vm based on qgis.vdi

### ISSUE THREAD

**Issue by zakigates** [qwat/QWAT#216]
Hi every one I have a serious issue right here. I'm tring to work with qwat on a VM, to do so I have to work with qgis.vdi and Oracle virtualbox. I followed the intructions described in tutorials about running a vdi in a virtualbox and every thing seems to be working well. Although when I start the vm it stops at the boot without returning any error to understand what is going wrong. If you can tell me what did I miss and what is exactly going on, I would be very thankful.

**Comment by tudorbarascu** [comment]
Hi, the VM should have just worked as it is already tested.
You're probably encountering local virtualbox problems.
Can you start other VM's under your virtualbox installation/is virtualization enabled in BIOS?
I'm afraid that regarding the virtualbox part you're on your own. You can also try using a trial of vmware etc to rule out virtualbox problems.
Good luck.

**Comment by tudorbarascu** [comment]
@zakigates I'm closing this issue as it's not relevant. I've retested the vm and it works.
