### ISSUE TITLE
Snapping features on QGIS 3 is problematic on qgep using node tool 

### ISSUE THREAD

**Issue by haubourg** [qwat/QWAT#218]
https://github.com/QGEP/QGEP/issues/330

This issue in QGEP concerns QWAT's needs. Duplicating it here to follow QWAT contributions

**Comment by haubourg** [comment]
duplicate of #193 >  closing

**Comment by haubourg** [comment]
Decision > 1/2 day of dev by Martin Dobias to add priority on node grabbing for active layer.

**Comment by ponceta** [comment]
This is done. Node is correctly grabbed!

**Comment by haubourg** [comment]
@dsavary: this also adresses the batch selection mode you asked me for yesterday. 
The behavior stays the same however for if you select over multiple features than in 2.18. And thinking of this, this is a good thing when editing common border to move all nodes. But yes, when you want to disjoin polygons, it's not easy to choose which polygon to grab currently I'm not clear on how to force which polygon to batch grab from a user point of view. any idea?. 
This can probably go in 3.2 however

**Comment by ponceta** [comment]
This issue can be closed since the bug is fixed. https://github.com/qgis/QGIS/pull/5149

Please move other potential issues in new issues.
