### ISSUE TITLE
QGIS : Copy + move + geom transformation 

### ISSUE THREAD

**Issue by ponceta** [qwat/QWAT#222]
I've been asked a tool like AutoCAD move which can copy and adapt a polyline or a spline to match same distance between all points which is great to draw schematic lines with a certain width in between.

![image](https://user-images.githubusercontent.com/8614223/30275326-45c6e906-9701-11e7-9b2d-31b54a3f5329.png)

It should be able to go from inner ring in to outer and reverse.

**Comment by 3nids** [comment]
offset curve map tool !

**Comment by ponceta** [comment]
Merci @3nids !

**Comment by 3nids** [comment]
@ponceta encore ça si jamais 
https://github.com/qgis/QGIS/pull/5195
