### ISSUE TITLE
QGIS : date calendar widget does not allow to select current value

### ISSUE THREAD

**Issue by ponceta** [qwat/QWAT#224]
![date](https://user-images.githubusercontent.com/8614223/30682628-9a43237c-9eaa-11e7-993c-f42690785de6.gif)

Tracking https://issues.qgis.org/issues/17173

**Comment by haubourg** [comment]
Confirmed !

**Comment by 3nids** [comment]
see original ticket https://issues.qgis.org/issues/13577

**Comment by ponceta** [comment]
Planned in QGIS bugfixing for November, assigned to @3nids

**Comment by ponceta** [comment]
This did not when in bugfixing, at last?

I've spotted some strange mechanism which can be great if you know how it works but dangerous for some users as it may issue some errors in the data.

There are some special interactions on the date format which enables to increase year, month day values using left click or scrolling when year / month / day is highlighted.

![date_increase](https://user-images.githubusercontent.com/8614223/33822497-08a7c768-de58-11e7-8377-3c75eeedf4a9.gif)

**Comment by 3nids** [comment]
not yet started on my side

**Comment by 3nids** [comment]
this has been fixed both in master and 2.18
