### ISSUE TITLE
QGIS : Snapping on intersections

### ISSUE THREAD

**Issue by ponceta** [qwat/QWAT#226]
Snapping on 3D layers intersections does not work:

On these particular cases :

- [x] between a 2D layer and 3D layer
- [x] between 3D layers
- [x] between line and cicurlar arc
- [x] between 2 circular arc
- [x] between polygon and circular arc

On :
 - [x] Memory layer
 - [x] Geopackage layer / not only on 3d layer
 - [x] Postgis layer
 - [X] Shapefile

**Comment by haubourg** [comment]
Works in all cases here

**Comment by haubourg** [comment]
I reopen that since I found that intersection of two circular Compound curves can't be snapped.

**Comment by dsavary** [comment]
Tests with QGIS 3.0
intersections don't work in these cases : 

- between a 2d layer and 3d layer (line, polygon, cicurlar arc) 
- between 3d layers (line, polygon, cicular arc)
- between line and cicurlar arc 
- between 2 circular arc 
- between polygon and circular arc 

for memory, shapefile, postgis, geopackage layer.

**Comment by 3nids** [comment]
is there an upstream ticket?

**Comment by ponceta** [comment]
LinestringZ regression :

![regression_snapping_intersections_qgis3](https://user-images.githubusercontent.com/8614223/53565122-d9dfe280-3b58-11e9-9097-6896d6abf8b1.gif)

**Comment by lbartoletti** [comment]
PR for intersection with Z and M in progress https://github.com/qgis/QGIS/pull/9379

**Comment by lbartoletti** [comment]
The PR works also for intersection with curve

**Comment by ponceta** [comment]
According to @lbartoletti 's latest developpements, I close this since it is now solved for us. Please feel free to open new issues for specific cases.
