### ISSUE TITLE
git submodules update fails

### ISSUE THREAD

**Issue by sebastian-r-schmidt** [qwat/qWat#23]
Hi, I Just tried to follow the install instructions and stumbled over the .gitmodules file. In my configuration, i could not do a git submodule update, it results in

"permission denied (public key).
fatal: Could not read from remote repository
Please make sure you have the correct access rights and the repository exists.
Clone of 'git@github.com:qwat/qwat-data-model.git' into submodule path 'data-model' failed.

When I look into .gitmodule and change the url from

url = git@github.com:qwat/qwat-data-model.git
to 
url = https://ghithub.com/qwat/qwat-data-model.git

it works out fine (after removing and re-intialising the sub-module).

I'm not sure what the git@github.com syntax for repositories means - is there a difference to the https url?

**Comment by tudorbarascu** [comment]
You're right. The url is better with the https option. The git@.. option is used when you're using ssh access (better for when you're using repositories a lot). As you probably didn't add your public key to github the command throwed that specific error.
Will change the README to take this into account.
All the best!

**Comment by tudorbarascu** [comment]
This can be closed..

**Comment by sebastian-r-schmidt** [comment]
Thanks for updating documentaion. Works for me - I'll close it.
