### ISSUE TITLE
Small bug on default value expression in forms

### ISSUE THREAD

**Issue by ponceta** [qwat/QWAT#232]
One can't select field names in expression tool for default values :

![image](https://user-images.githubusercontent.com/8614223/31425990-cfe1c8f0-ae61-11e7-892d-8ab8cee50e2c.png)

Works well two lines further in expression tool for constraints :

![image](https://user-images.githubusercontent.com/8614223/31426014-e1b4be34-ae61-11e7-9dd7-73a524565191.png)

Tested on QGIS 2.18.13 (win x64) on text edition form.

**Comment by ponceta** [comment]
https://issues.qgis.org/issues/17268 For QGIS hub following

**Comment by haubourg** [comment]
Confirmed,  on 2.18.10 and master 2.99 too. 
@pblottiere any idea why the default values expression scope doesn't show fields? Is that by design or just forgotten somewhere?

**Comment by haubourg** [comment]
That can't be done: see Nyall's comment. This isn't possible. 
>The default values are calculated on new feature creation, which is before any values are available for the feature's other fields.
I close that
