### ISSUE TITLE
[Forms] Constraint visibility on multiple tabs forms

### ISSUE THREAD

**Issue by ponceta** [qwat/QWAT#235]
Actually, having constraints on forms is sometimes not so obvious to correct, specially if you don't know in which tab is the field not fitting the constraint.

![image](https://user-images.githubusercontent.com/8614223/32161545-429d131a-bd56-11e7-90fa-ed756c9ceec5.png)

A good visual help could be to color the tabs labels where constraint is not fitted.

And display tabs names before fields names in the constraint warning.

Thoughts?

**Comment by m-kuhn** [comment]
+1 for tab colors.
Constraint warnings are gone from the top. They remain on the label itself, so this becomes even more important.
If you want, I can give it a go.

**Comment by ponceta** [comment]
Now part of QGIS project!
