### ISSUE TITLE
Improve Datum handling for copy/paste in QGIS

### ISSUE THREAD

**Issue by haubourg** [qwat/QWAT#236]
Datum handling in current master and qgis 2 isn't using correctly datum transformations, which can lead in geometry precision loss when copy/pasting features from between two SRS using differente datum, which is the case in switzerland between new MNT95 and old SRS. 

Discussion previously occured in QEP 100:  https://github.com/qgis/QGIS-Enhancement-Proposals/issues/100 
QWAT group decided to get involved on the 20/10/2017 to fix that. Core work is asked to Nyall Dawson and Graphical improvements can ben done by @3nids . 

See the following PR in progress here https://github.com/qgis/QGIS/pull/5535

**Comment by haubourg** [comment]
@3nids I saw  your comment here  https://github.com/qgis/QGIS/pull/5535#issuecomment-343388781We still have one day remaining in the budget for code review. Can I ask @pblottiere  to spend a day on that? 
ping @ponceta

**Comment by 3nids** [comment]
@haubourg I'm on the UI now, might be worth waiting for it to be done. Then if Paul feels like going through this it would be awesome, we just need a guy who feels confident with datum concept (which is not my case ;) )

**Comment by haubourg** [comment]
part 1 is done. Invoice received today .

**Comment by haubourg** [comment]
PR merged 
https://github.com/qgis/QGIS/pull/5906
https://github.com/qgis/QGIS/pull/5898
https://github.com/qgis/QGIS/pull/5535
