### ISSUE TITLE
Demo project

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/QWAT#24]
Hi,

I think that in the future we should have a demo project (English would be best but French would be ok for starters) with some created data so that others can better grasp the functionalities.

**Comment by schoeller** [comment]
@tudorbarascu @3nids : I took the liberty and contacted Rui Pina for the <code>qgis-epanet</code> sample which is a real life hydraulic modelling example, but by nature limited to information required for modelling. He's unsure whether the dataset available under https://github.com/vmora/qgis-epanet/tree/master/examples/aguas_de_coimbra is suitable for the job, but he's open for discussion whether it may be used and asked me to contact the QWAT developers first. Please feed back on what you think.

**Comment by vpicavet** [comment]
Sample data should be provided by Lausanne or Pully soon.

**Comment by vpicavet** [comment]
See https://github.com/qwat/qwat-data-sample
