### ISSUE TITLE
[Documentation]

### ISSUE THREAD

**Issue by ponceta** [qwat/QWAT#242]
Proposals:
 - [x] Qwat doc in a specific repo : eg. qwat/docs?
 - [x] Qwat doc translation in transifex?
 - [x] Fix or workaround  current issues with readthedocs builds (failing because of submodules)

Thoughts?

**Comment by ponceta** [comment]
Ping @haubourg is there much work to make current doc "transifexable"?

We should only provide the tools and the base documentation, the crowd should provide the rest!

**Comment by haubourg** [comment]
Well yes good idea, though the message I ear from the board is not so oriented to a community based approach. 
However currently, I don't think even a transifex is simple enough to be easily accessible by the very few potential contributors.  
If you look at the QGIS translation process, it is not simple at all and this prevents many users to jump in. 
Even sphinx RsT is a barrier (to me at least).  
And the cost of having a continuous integration / build infrastructure for so few people suggests me to just work on the content right now, and when it's correct, see if we can improve the infrastructure.

**Comment by ponceta** [comment]
This has been adressed, QWAT documentation is now multilingual and available here :
https://qwat.github.io/docs/master/en/html/
Anyone can join the translation team on transifex.
