### ISSUE TITLE
QGEP add separated roles admin, user, etc..

### ISSUE THREAD

**Issue by haubourg** [qwat/QWAT#253]
Work done by @3nids (along with dispatch tables in schemas and PUM integration )

Related issues :

[  ] https://github.com/QGEP/QGEP/issues/403

**Comment by 3nids** [comment]
I think this can be closed

**Comment by haubourg** [comment]
the group raise the issue that we miss documentation for the roles in readthedocs. @lbartoletti can you check the status of the doc?
