### ISSUE TITLE
QGEP dispatch tables in schema for easier management

### ISSUE THREAD

**Issue by haubourg** [qwat/QWAT#254]
The database structure will follow the QWAT's one with : 

*_od : schema for ordinary data (actual user data)
*_vl: value lists 
*_sys: system tables like version for PUM, audit logs

To be noted, QGEP now has a qgep_api schema which stores the stored procedure. This is a good practice that would be nice to have in QWAT too.

**Comment by 3nids** [comment]
You would move existing stuff to qwat_api ?

**Comment by haubourg** [comment]
@3nids  
I just opened a ticket to have on going actions in the qwat's dashboard, no action required here :)

We've been discussing about thick database practices a few times. A refactor to use only views, limit cascaded views to 2 levels max, limit triggers on tables when calculated views can do the work, store and organize stored procedures in a dedicated schema,  is always a good thing. 
I'd like to see this happen in the future in QWAT since jumping into QWAT DB structure and dev seems not so easy in the current state.

**Comment by haubourg** [comment]
Yep, done thanks
