### ISSUE TITLE
Create Documentation

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/QWAT#26]
I think that we should start sooner or later with the documentation
Should it be done using Github pages or sphinx docs or maybe something else?
English version as base?
I have experience using sphinx/markup language so I can help here.

**Comment by ldgeo** [comment]
Hello, 
i think that sphinx is a good choice combined with readthedoc for automation.
i don't have access to the repo settings, @3nids could you activate the ReadTheDoc service in settings ? I will next create a account on readthedoc, configure it and add the initial structure of documentation.

**Comment by 3nids** [comment]
Hi @ldgeo just done it.

**Comment by ldgeo** [comment]
thanks, bootstrapped in 2de821fd912885fabc8e0b231d5c44453cdd30ed.
Needs come contents now :pencil2:

**Comment by tudorbarascu** [comment]
@ldgeo Hi and thanks for joining.
I think that we should have a separate docs repo so that we separate things from the start.
What do you guys think?

**Comment by ldgeo** [comment]
if the doc targets the data-model too, yes it's a good thing since data-model is in its own repo. 
Having a documentation that covers all qwat's stuff is neat.
In the same lines, moving the qwat-dictionnary in a seperate repo will be a good thing, it will be easier to publish it in the official qgis plugin repository.

**Comment by vpicavet** [comment]
See #82 and #81 too. 
@ldgeo Is your doc boostrap ready for i18n ? if not can you patch it for that ?

**Comment by ldgeo** [comment]
@vpicavet not yet, i don't think readthedoc has support for internalization.
But i can already add sphinx-intl which add i18n support to sphinx.
So the default writing language will be French or English?

**Comment by haubourg** [comment]
doc infrastructure is present. Closing, please create a more specific issue
