### ISSUE TITLE
[QGIS] improve CAD editing tools in QGI3

### ISSUE THREAD

**Issue by haubourg** [qwat/QWAT#274]
@lbartoletti work on CAD editing enhancements https://github.com/qgis/QGIS-Enhancement-Proposals/issues/106 is a global roadmap for new or improved editing tools inspired by CAD workflows.

QAD plugin and CADditigitizing plugin offer good prototypes or temporary features to wait for things to be contributed in Core

Already done in QGIS3: 

- new regular shape toolbar
- new node tool
- advanced digitizing panel useable with most editing tools
- preserve z values when editing
- various fixes

**Comment by lbartoletti** [comment]
Update:
- reverse line tool added
- trim/extend tool in progress

**Comment by ponceta** [comment]
This can be closed. Not a QWAT issue anymore.
