### ISSUE TITLE
Travis / PUM error

### ISSUE THREAD

**Issue by lbartoletti** [qwat/QWAT#275]
See [this log](https://travis-ci.org/qwat/qwat-data-model/builds/363962464):
```
Initialize databaseusage: pum [-h] [-V] [-c CONFIG_FILE]
           {check,dump,restore,baseline,info,upgrade,test-and-upgrade} ...
pum: error: unrecognized arguments: -v
```

**Comment by sylvainbeo** [comment]
@lbartoletti C'est -v pas -V (?)

**Comment by sylvainbeo** [comment]
> optional arguments:                                                                                                                                                                                                
  -h, --help            show this help message and exit                                                                                                                                                            
  -v, --version         print the version and exit                                                                                                                                                                 
  -c CONFIG_FILE, --config_file CONFIG_FILE                                                                                                                                                                        
                        set the config file

**Comment by 3nids** [comment]
I just changed this to avoid confusion because -v was already used for verbosity in subcommands.
I can revert.
