### ISSUE TITLE
[QGIS] - in read-only mode, the drop-down list (combo box) on a form can be "edit"

### ISSUE THREAD

**Issue by dsavary** [qwat/QWAT#277]
QGIS 2.18.18 : if you open a form on a read-only layer, you can now consult the value list. 
Is it a bug ? or a new  request from the QGIS users community ?
The user cannot update the value in DB, but can read the wrong information on the form. 
![combo_box_readonly](https://user-images.githubusercontent.com/6229296/38659816-98182d12-3e1a-11e8-8081-0b4798c60bc3.png)

In our opinion (Lausanne), it's better that the combo box is locked in read-only mode :)

**Comment by haubourg** [comment]
Hi Daniel, 
it looks like a bug to me and I confirm that behavior. Didn't it appear before 2.18.18 ? 
It seems also there in QGIS 3. 
I let you priorize that with the User group if you want us to have it fixed.

**Comment by ponceta** [comment]
![image](https://user-images.githubusercontent.com/8614223/53645461-34e90680-3c39-11e9-8d3f-c8b33afa1501.png)

3.4.5 Fixed? @dsavary could you please check?
