### ISSUE TITLE
Use diameter data driven properties to draw pipes

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/QWAT#28]
Hi Denis,

As I've been using this feature for a long time, I am wondering if you guys also want it.
Sometimes, it's more helpfull to watch the rendered pipes and figure out which is larger than to look at the labels.

This is how it looks like for us. All the pipe lines are drawn with a minimum width.

![data_driven_pipe_properties](https://cloud.githubusercontent.com/assets/3179646/8744383/7861977e-2c7f-11e5-8b1e-feeb053be51f.png)
![data_driven_properties](https://cloud.githubusercontent.com/assets/3179646/8744384/78631180-2c7f-11e5-9af8-f1e5e50d7e8c.png)

**Comment by 3nids** [comment]
yes, I am thinking of using this too.
I would use min and max width

**Comment by tudorbarascu** [comment]
As I am using a minimum width for the case where pipe diameter is unknown and to have a minimum good rendered pipe line, to what case have the max width refers to?

I was just thinking that maybe it would be easier if we would add a line_width column to the materials table as the current rules are somewhat long. e.g.

CASE WHEN "pipe_material_a_code_sire" = 10 THEN toreal("pipe_material_a_diameter_external") / 900 + 0.2 WHEN "pipe_material_a_code_sire" IN (2, 6) THEN toreal("pipe_material_a_diameter") / 900 + 0.2 ELSE toreal("pipe_material_a_diameter_nominal") / 900 + 0.2 END

If you think it's a good idea I can work on it and make a pull request.

**Comment by 3nids** [comment]
I was just thinking to avoid lines getting too large, but I did not try.

An easier expression would be something like:

COALESCE("pipe_material_a_diameter_external","pipe_material_a_diameter",toreal("pipe_material_a_diameter_nominal")) / 900 + .2

Not sure it is worth adding in the data model.
It could also be a virtual column in QGIS.

**Comment by tudorbarascu** [comment]
Yes, it is simpler with COALESCE, I can't recall why I choose differently then - lack of knowledge probably. Still, we need to account for the special cases where the diameter is unknown.
Would you go for a virtual column?

**Comment by 3nids** [comment]
I would prefer to stick to expressions, as I did for rules, but I don't mind a virtual column!

**Comment by tudorbarascu** [comment]
Solved by https://github.com/qwat/QWAT/pull/29
