### ISSUE TITLE
QGEP plugin fixes

### ISSUE THREAD

**Issue by haubourg** [qwat/QWAT#283]
@ponceta asked for fixes and changes of the QGEP plugin . 

See https://github.com/QGEP/QGEP/issues/406

````
When digitizing reaches with QGEP plugin editing wizard

    QGIS visual snapping indicators are not shown
    Z coordinate is not taken into account (2D geometry is created)
```

Work clearance given on the 8th of May. 

<!---
@huboard:{"order":82.79268233510135,"milestone_order":0.9978025279772647,"custom_state":"blocked"}
-->

**Comment by haubourg** [comment]
@3nids any news of the status of this work - required by early/mid  june?

**Comment by haubourg** [comment]
Sorry it can't, Arnaud doesn't get 3d vertices created when ditgitizing a reach that is snapped on a 3D feature. Can you provide a the SQL definition samples that you show in your screencast so that we can check we don't hit another corner case ?

**Comment by 3nids** [comment]
sorry, a bit confused by different sources of info....can this be closed now?

**Comment by haubourg** [comment]
Done (I'm also confused by the 3 involved bug trackers :/ )
