### ISSUE TITLE
altitude object reference in surveying and in the database

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/QWAT#290]
Hello!
I was wondering how are you guys handling the object reference for altitude in table qwat_vl.object_reference

For now, we have:
```
   value_fr   
--------------
 autre
 inconnu
 à déterminer
 radier
 sol
 conduite
 dessus
```
and I am wondering if "conduite" means for you that is on the axis of the pipe, or on top of it?
The reason I'm asking is that we're analyzing our surveying workflows for valves and of course, when you survey with the GPS or with a total station you sometimes can get the altitude on top of the pipe (not the axis).
So, some of my surveying colleagues thought that "pipe" means on top of it, as that's how they capture the data while for me it's the altitude of a water element node with relation to the pipe is always on the axis as it's far more usable later on. 

I'm thinking that we could have have two altitude values describing the reference to the pipe ("pipe axis" and  "on top of pipe" or something). The surveying guys get the altitude "on top of pipe" and can put it like that in the database and someone (they, database triggers or the manager) subtract later half of the pipe diameter to calculate the node position while changing to the "pipe axis" value.

I think that depending on what you guys say we could be explicit in the description_fr, description_en etc..
so that we can all be consistent if we're not.

Thoughts?

**Comment by haubourg** [comment]
Hi Tudor, very good question, I think we can address that to QWAT's user groups. 

As a (weak) reference, the [French GeoStandard RAEPA](http://www.geoinformations.developpement-durable.gouv.fr/geostandard-reseaux-d-adduction-d-eau-potable-et-d-a3478.html) states the following: 

Wastewater water pipes are described by the "fil d'eau" reference, ie the water level  of the bottom of a reach. 

Drinkable waster pipes only have an altitude and no reference attribute to explain where the altitude is measured. It is up to the users to adopt a common reference.

**Comment by tudorbarascu** [comment]
@qwat-psc It would be great to see what's your opinion so that we can standardize what's the meaning or just add both options in the next qwat model.

**Comment by dsavary** [comment]
@tudorbarascu we use the value "object reference" only for surveypoints. 
the value "conduite" is not very clear. 
For QWAT, we use almost always "on the pipe" , sometimes we use : without altitude, ground, on control valve. We don't move the coordinate "z" of the pipe after the surveying.
For QGEP, we use often the value "on the pipe" and "radier" (bottom) . For the points "on the pipe", we move the "z" coordinate of the pipe to the "radier" (bottom) level. (drawndown of the pipe -> action taken by the users)

**Comment by ponceta** [comment]
@tudorbarascu I can confirm that in Pully we measure altitudes on the pipes, which is the default value for all our objects in our water network.

Like Lausanne, we do not move these coordinates.

This is not the axis altitude but regarding of the pressure, this is not as relevant as on wastewater network. (as long as it is clear that it is "on the pipe" altitude)

**Comment by tudorbarascu** [comment]
@ponceta @dsavary @lbartoletti Then I would change the default altitude to ``dessus de la conduite`` and add another value with ``axe de la conduite``.

As all of you work with the altitude meaning on top of the pipe then it's an easy migration ( don't have to do anything) but things would me much cleaner and we also introduce the pipe axis needed for hydraulic modelling.

As a bonus, we could also improve the ``dessus`` value and be more explicit with something like ``dessus l'element`` which would be different meaning than that of on top of pipe.

I want to make a pull request.. does this look good to you?
```
diff --git a/value_lists/vl_object_reference.sql b/value_lists/vl_object_reference.sql
index 27db92e..230ae2d 100644
--- a/value_lists/vl_object_reference.sql
+++ b/value_lists/vl_object_reference.sql
@@ -15,8 +15,10 @@ INSERT INTO qwat_vl.object_reference (id, value_en, value_fr, value_ro) VALUES (
 
 INSERT INTO qwat_vl.object_reference (id, value_fr, value_en, value_ro) VALUES (9001,'radier','apron','radier');
 INSERT INTO qwat_vl.object_reference (id, value_fr, value_en, value_ro) VALUES (9002,'sol','ground','sol');
-INSERT INTO qwat_vl.object_reference (id, value_fr, value_en, value_ro) VALUES (9003,'conduite','pipe','conductă');
+INSERT INTO qwat_vl.object_reference (id, value_fr, value_en, value_ro) VALUES (9003,'dessus de la conduite','on top of pipe','pe conductă');
 INSERT INTO qwat_vl.object_reference (id, value_fr, value_en, value_ro) VALUES (9004,'dessus','on top','deasupra');
+INSERT INTO qwat_vl.object_reference (id, value_fr, value_en, value_ro) VALUES (9005,'axe de la conduite','pipe axis','axul conductei');
```

**Comment by lbartoletti** [comment]
@tudorbarascu LGTM
@ponceta @dsavary is it good for you too?

**Comment by tudorbarascu** [comment]
Just daydreaming here, I would love to see: 
- the 3d pipes created with z based on the axis height and not on the "top of the pipe"
- the creation of the 3d pipe based on database side logic, and not on QGIS side. I've thought about this a lot and it's a necessary thing for the model stability/testing as it's far less error prone IMHO

**Comment by ponceta** [comment]
Good to me too.

@tudorbarascu daydreaming here would be to have actually more than 90% of 3D data...
