### ISSUE TITLE
QGIS 3.X node A and node B are not filled automatically for pipe

### ISSUE THREAD

**Issue by ponceta** [qwat/QWAT#295]
Nodes IDs are not filled automatically at pipe insertion on QGIS 3.X

![image](https://user-images.githubusercontent.com/8614223/53564338-ebc08600-3b56-11e9-9ca0-173e9338b110.png)

Their NOT NULL constraint requires some values before allowing the user to validate his form.

**Comment by ponceta** [comment]
Workaround : set 1 as default value, wait for fix in QGIS 3.4.6

**Comment by haubourg** [comment]
Solved in QGIS 3.4.7 and in QGIS3 migration
