### ISSUE TITLE
Water meter labeling

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/QWAT#31]
Hi,
What does RES stand for regarding the water meters labeling?

**Comment by tudorbarascu** [comment]
@3nids Good morning! 
I still haven't figured out what does the 'RES` part does from `identification || '#!#RES`..

**Comment by 3nids** [comment]
I thik I used the #!# as a new line character.

**Comment by 3nids** [comment]
RES is a short name for réseau (network)

**Comment by tudorbarascu** [comment]
Thanks!
