### ISSUE TITLE
Feature request: include irrigation / watering

### ISSUE THREAD

**Issue by tproduit** [qwat/QWAT#325]
In our communes, we have two kinds of networks: one for drinking water, one for irrigation. Sometimes both networks share some network elements. Another scenario, is a part of the drinking water which is used for irrigation.

We tried two strategies:
* implement one QWAT DB for drinking water and another for irrigation 
   Pros:
   * Networks are separated
   
   Cons:
   * Shared elements are duplicated
   * Edition must be done in two DB / two QGIS projects
   * Network elements of the drinking water network used for irrigation are not connected to the network
  
* have both networks in one DB and use the watertype to separate the networks 
   Pros:
   * There is a single DB for the edition and the maintenance
   
   Cons:
   * The attribute watertype contains the water quality. We could have drinkable water in the irrigation system. We can have not drinkable water in the drinking water supply network (upstream the treatment) > There is a confusion
   

They are both not satisfactory. In my opinion, we might consider to add a new attribute (network element function). The functions might be: drinking water supply, irrigation supply and other.

**Comment by ponceta** [comment]
In Pully we use the distributor as an attribute to distinguish these two distribution types.

Irrigation is slightly lighter blue.

![image](https://user-images.githubusercontent.com/8614223/213184224-bff27dd8-abdf-405c-a350-170b9313e74d.png)

I'm open to suggestions.

**Comment by tproduit** [comment]
Indeed, this is a good idea. We implemented it. In my opinion, we can use this "trick" and close the issue.
