### ISSUE TITLE
Add water meter boolean to installation chamber

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/QWAT#44]
I think that It would be a good enhancement to also add a water meter boolean to the chamber installation.
This would necessitate that the current `meter` be renamed to somethink like `flowmeter`.

**Comment by tudorbarascu** [comment]
Will work on it and make a pull request. Please say if you think that I should do otherwise.
Thanks!

**Comment by 3nids** [comment]
+1, good for me!
