### ISSUE TITLE
Syntax error in od_node.sql

### ISSUE THREAD

**Issue by schoeller** [qwat/QWAT#45]
Dear all,

first of all thanks for your efforts in order to bring a solution like this to QGIS.

I am not a skilled developer, just a civil engineer trying to evaluate different possible solutions. I am running Windows 7 and Postgres 9.4.4 and Postgis 2.1.8. When executing the data-model installer from the git command line I receive the error

<code>
psql:ordinary_data/nodes/od_node.sql:58: FEHLER:  Syntaxfehler bei â?z%â?o
LINE 1: COMMENT ON TRIGGER %1$I ON qwat_od.node_altitude_update_trig...
</code>

I assumed that the git-client environment is shell compatible meaning that I have not tried from a UNIX command line. When reviewing the test database I see only

<code>
qwat_od.ft_node_altitude
</code>

as a registered function. Installation assistance is highly appreciated.

Best wishes

Sebastian

**Comment by 3nids** [comment]
Hi Sebastian,
Sorry for the troubles, I am doing a major upgrade in the data model, and (not a good thing) I am working on the master branch.
I will need about 2 more days to finish this work.
I'll let you know as soon as it is ready.
Sorry again.
Denis

**Comment by tudorbarascu** [comment]
@schoeller Hi Sebastian, adding to what Denis just said, if you don't want to wait and test a working setup then just checkout the data model to a working commit like https://github.com/qwat/qwat-data-model/commit/4b6bd451c9a6ac15fae4c5a4613c9c77e026b0e9 by doing `git checkout 4b6bd451c9a6ac15fae4c5a4613c9c77e026b0e9`
It should match the current qWat repo as I have already tested it.
Please post here if you encounter other problems.

**Comment by schoeller** [comment]
@tudorbarascu Hi Tudor, I have done as told and now I receive the error

<code>
psql:ordinary_data/installation/vw_installation_views.sql:47: FEHLER:  Funktion
qwat_sys.fn_inherited_table_view(json) existiert nicht
LINE 1: SELECT qwat_sys.fn_inherited_table_view(
</code>

I figured that the function <italic>fn_inherited_table_view</italic> is defined in https://github.com/3nids/pg_inherited_table_view/blob/master/pg_inherited_table_view.sql, which does not seem to be called during installation.

**Comment by schoeller** [comment]
I just noticed that it is indeed called in the installation script

<code>psql -v ON_ERROR_STOP=1 -v SCHEMA=qwat_sys -f metaproject/postgresql/pg_inherited_table_view/pg_inherited_table_view.sql</code>

so I would expect the function to be defined under qwat_sys, but there is none. I will have to wait for Denis sign.

**Comment by tudorbarascu** [comment]
It works just fine for me.
I have made a custom dump of a newly created database. You need to add a new distributor in the distributor table before starting to create any other water elements otherwise you won't be able to save them.

You can dowload the dump from https://www.dropbox.com/s/jg3ydipd7fy01n6/dumpqWat.backup?dl=1

**Comment by schoeller** [comment]
@tudorbarascu Database restore worked out for me. Now the database connection itself is troublesome. I can access the database within Qgis without doubt. When opening the project file <em>qwat.qgs</em> though I get connection errors. I went forward and defined a system variable called
<code>PGSYSCONFDIR</code>
as defined on http://qgep.github.io/docs/installation-guide/system/workstation.html. I am asked several times about authentification and I enter the valid details. The loading bar then continues from 6% to 100%. I then receive a warning about missing data, which comprises 76 layers. Is this the correct user behaviour or is my database connection still not well configured?

**Comment by tudorbarascu** [comment]
@schoeller If you saved  the file in unix format like it's described in that documentation, it should be ok.
Opening up the project should not give any error if you have a correctly filled `pg_service.conf` and if the database security lets you.

You also need to restart the windows box to get the PGSYSCONFDIR variable working..

**Comment by schoeller** [comment]
@3nids tried the new database model. Checked out freshly. When running install script it cannot find <code>pg_inherited_table_view.sql</code>. After checking that out from https://github.com/3nids/pg_inherited_table_view I still get the same error as initially. I hence fixed the schema name to <code>qwat_sys</code> and altered the installation script to read <code>psql -v ON_ERROR_STOP=1 -f metaproject/postgresql/pg_inherited_table_view/pg_inherited_table_view.sql</code>. I then re-ran the database setup script. The function is now existing in the database, but I still receive the error
<code>psql:ordinary_data/installation/vw_installation_inheritance.sql:44: FEHLER:  Fun
ktion qwat_sys.fn_inherited_table_view(json) existiert nicht
LINE 1: SELECT qwat_sys.fn_inherited_table_view(</code>

When checking for the defined function I noticed that it reads
<code>fn_inherited_table_view(json, json[], text)</code>
Could the difference in arguments in function definition and function call make the difference?

**Comment by schoeller** [comment]
just realized that <code>data-model</code> contains another submodule. So I ran <git submodule init && git submodule update</code> within the <code>data-model</code> subdirectory and then the install script passed without errors.
