### ISSUE TITLE
Enhancement to installation form regarding nodes

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/QWAT#47]
I just noticed the fk_node doesn't have a corresponding widget in the installation buildings.
I think it would be good if we add one.
Moreover, as we're using another layer pointing to the same db table using the geometry_polygon, we're inclined towards a relation widget so that when creating polygons we can select the node.
This would save us a step by not creating first the feature on the installation_buildings point layer.

Do you think that the default qwat.qgs project would also benefit from adding an installation building polygon layer?
Should I add the widget and/or a polygon layer or do you have any thoughts on this?

**Comment by 3nids** [comment]
You're looking at the old model....
Now installations are network_elements which are nodes themselves.
No foreign key anymore, we use inheritance.

Also, there is no more an installation building table.

**Comment by 3nids** [comment]
the QGS file is not ready yet, I'll have it by tomorrow evening hopefuly

**Comment by tudorbarascu** [comment]
I meant to talk about the vw_qwat_installation view but as I was used to call it installation building... it came out that way.
Afte you created that view, you only made a layer based on the point column and I am thinking of another layer based on the geometry_polygon one.
Basically, I'm thinking about the workflow where the features are created using the layer based on the polygon geometry.

I'm eager to see the new project.

**Comment by 3nids** [comment]
that was the intermediate model (pump inherits installation which is linked to node).
Now pump -> installation -> element -> node

**Comment by tudorbarascu** [comment]
Cool as hell! :)
