### ISSUE TITLE
Cannot add nodes

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/QWAT#50]
```
Could not commit changes to layer noeuds

Errors: ERROR: 1 feature(s) not added.
  
  Provider errors:
      PostGIS error while adding features: ERROR:  Column has Z dimension but geometry does not
```

**Comment by tudorbarascu** [comment]
At first look, by using the old check constraints behavior on the node table fixes the problem.
Are you exhibiting the same problem?
Thoughts?

**Comment by 3nids** [comment]
When does this occur?
You're not supposed to create nodes yourself (I won't issue a fine though ;) )

**Comment by tudorbarascu** [comment]
It occurs when creating nodes.
I was thinking of creating nodes with different altitudes and draw a pipe between them and see the 3d length etc.

**Comment by 3nids** [comment]
The way to go would be to create survey points.
Although the mechanism of transferring the altitude to the nodes is not determined yet.
