### ISSUE TITLE
qwat.qgs is claiming service='sige_commun' while opening

### ISSUE THREAD

**Issue by schoeller** [qwat/QWAT#61]
Hi and thanks for the work,

after having installed the database according to the README I open up the <code>qwat.qgs</code> project file. As a testing user I expect a demo project to be loaded so that I may fiddle around. Instead I get a message from QGIS 2.10 saying that the database service <code>service='sige_commun'</code> should specified since it cannot be found within the standard database. There is a demo dataset available from <code>qgis-epanet</code> at https://github.com/vmora/qgis-epanet/tree/master/examples/aguas_de_coimbra. Would it be possible to provide the user with this dataset?

Best wishes

Sebastian

**Comment by tudorbarascu** [comment]
We are planning on having a demo data project in the near future, see https://github.com/qwat/QWAT/issues/24 and https://github.com/qwat/qwat-data-model/issues/69

For now, the sige_commun service points to data that's specific to SIGE (cadastral data, rasters etc.).
You should ignore that and simply start the project as it is.
The first thing you should do is add a value to distributors list  (e.g. X water company), and afterwards.. simply add pipes, valves and other elements.

**Comment by tudorbarascu** [comment]
Hopefully, we'll make a nice demo data, and we'll take into account that demo data link.
All the best Sebastian!

**Comment by schoeller** [comment]
@tudorbarascu: After having cancelled unknown data sources I added to the layer <code>Tables auxiliaires / distributeur</code> a distributor. I now can edit other layers in order to test functionality.

**Comment by tudorbarascu** [comment]
@schoeller I think you can close this down if you don't have any issues anymore.
