### ISSUE TITLE
An error in od_pipe.sql ?

### ISSUE THREAD

**Issue by sylvainbeo** [qwat/QWAT#70]
It seems to have an error in od_pipe.sql.

Those 2 lines should be inverted :
ALTER TABLE qwat_od.pipe ADD COLUMN year_rehabilitation smallint CHECK (year_end IS NULL OR year > 1800 AND year < 2100);
ALTER TABLE qwat_od.pipe ADD COLUMN year_end smallint CHECK (year_end IS NULL OR year > 1800 AND year < 2100);

**Comment by tudorbarascu** [comment]
Hi @sylvainbeo
I think you're looking at older variant.
Those lines are not the same as  you presented in the [current od_pipe.sql](https://github.com/qwat/qwat-data-model/blob/master/ordinary_data/pipe/od_pipe.sql)
If not, then please give extra details on what's wrong.
Thanks.

**Comment by sylvainbeo** [comment]
Yes. Nevermind. The data-model branch was not up to date. Sorry.
