### ISSUE TITLE
fme scripts

### ISSUE THREAD

**Issue by ldgeo** [qwat/QWAT#71]
Hello, 
is anyone still using the fme scripts in the sources (tools/fme/) ?

**Comment by 3nids** [comment]
They were use for migration. I don't care removing them, but they might source of inspiration for someone movng from topobase 2. What do you think?

**Comment by tudorbarascu** [comment]
Hi guys, what do you think about moving the scripts to another repo:  ``qwat/topobase_migration``

**Comment by ldgeo** [comment]
Hi, good idea to move it to another repo, @3nids is it ok for you ?

**Comment by 3nids** [comment]
good to me, will do it.

**Comment by vpicavet** [comment]
I created the repo : qwat/topobase-migrator

**Comment by 3nids** [comment]
ok, done!
