### ISSUE TITLE
Z coordinate management ( altimetry)

### ISSUE THREAD

**Issue by vpicavet** [qwat/QWAT#74]
The altitude ( z coordinate) is stored inside QgsGeometry objects. We can access it via an expression ```z($geometry)```

The z coordinates of vertices should now be displayed and editable in the node tool dock. It does not seem to work with the PostGIS driver.

**Comment by mhugo** [comment]
I've just tested in the last master, and there is "Vertex editor" dock widget that allows to edit thz Z coordinate of a node.
Successfully tested on two postgis tables with 3D points and 3D linestrings

**Comment by 3nids** [comment]
main problem is when creating new features, not editing.
If you have create geometry column using postgis 2 (ALTER TABLE...ADD COLUMN) and not v 1 (AddGeometryColumn), you can't commit the feature.

**Comment by mhugo** [comment]
Indeed, reproduced. I am on it

**Comment by mhugo** [comment]
PR https://github.com/qgis/QGIS/pull/2703

**Comment by mhugo** [comment]
Merged in master. To be tested

**Comment by vpicavet** [comment]
Closing, Reopen if commited code has problems
