### ISSUE TITLE
SIRE format export

### ISSUE THREAD

**Issue by vpicavet** [qwat/QWAT#76]
A set of export script should be available for SIRE format

**Comment by 3nids** [comment]
The idea is to have view in a dedicated schema.
Then to use a plugin within QGIS to determine what window should be extracted and maybe select objects. Then we would ogr2ogr directly to write to shapes.

Note: we can use subprocess.call( 'ogr2ogr params' ) within qgis, and it calls the one installed along qgis (for windows).

**Comment by tudorbarascu** [comment]
out of curiosity, what does the SIRE format serves and why isn't it in Spatialite.

**Comment by vpicavet** [comment]
@tudorbarascu some info here ( FR, you can google translate it) : 
http://www.vd.ch/themes/environnement/eaux/eau-potable/systeme-dinformation-des-reseaux-deau-sire/

**Comment by tudorbarascu** [comment]
@vpicavet Thanks for the info!
I won't be needing translation since I can read/speak French.

**Comment by haubourg** [comment]
Hi, can we close this issue. I assume the export views are doing the work already?

**Comment by haubourg** [comment]
@3nids Can we close that Denis?

**Comment by 3nids** [comment]
Still open, we will tackle this by the end of the summer

**Comment by ponceta** [comment]
PR for SIRE improvements

 - [ ] Improvements to export views
https://github.com/qwat/qwat-data-model/pull/217
 - [ ]  Small fix for remote when enabling SIRE extension
https://github.com/qwat/qwat-data-model/pull/216
 - [ ] missing classes/attributes for SIRE (issue)
https://github.com/qwat/QWAT/issues/247

This is the first step to be "SIRE ready"

**Comment by ponceta** [comment]
About SIRE :
https://www.vd.ch/fileadmin/user_upload/organisation/dse/scav/sire/FlyerA4final.pdf

SIRE Essentials + Mandatory data/attributes :
https://www.vd.ch/fileadmin/user_upload/organisation/dse/scav/sire/Final_DirectivesDonnee_4.1.pdf

SIRE MCD :
https://www.vd.ch/fileadmin/user_upload/organisation/dse/scav/sire/Dictionnaire4.6.pdf

**Comment by haubourg** [comment]
Work done according to Pully and SIGE. Please reopen if necessary
