### ISSUE TITLE
Log management improvement

### ISSUE THREAD

**Issue by vpicavet** [qwat/QWAT#77]
The current way of logging information and storing history for the data can be improved

**Comment by 3nids** [comment]
From last discussions with Vincent, the idea would be to keep current mechanism (log every action in a dedicated table).
There has been some improvements on QGIS side to write fields and geometry updates at once for PostgreSQL (https://github.com/qgis/QGIS/commit/ad1fd2a922777ad048f2726341e9c09bc39128b9)
First need is to move the trigger from the low-level tables to the generated view (used for joining inherited tables). This should be straightforward though.
Second step is to provide some SQL methods to revert changes.
Last step would be to provide a nice UI in a plugin to look for changes and revert.

**Comment by vpicavet** [comment]
Specific issues for further steps have been created.
Last item before closing this is moving triggers to generated views. 
@sylvainbeo will take this action in the next days.

**Comment by haubourg** [comment]
closing since later tickets handle that - PR almost merged
