### ISSUE TITLE
QGIS Node editing tool as freehand tool ( aka "click-click")

### ISSUE THREAD

**Issue by vpicavet** [qwat/QWAT#78]

**Comment by 3nids** [comment]
See last discussion (with references to other discussions): https://lists.osgeo.org/pipermail/qgis-developer/2016-January/040962.html

**Comment by vpicavet** [comment]
See upstream ticket : https://hub.qgis.org/issues/14112

**Comment by 3nids** [comment]
any news from Martin on this?

**Comment by vpicavet** [comment]
Yes, he agreed and will start QEP/implementation probably next week

**Comment by 3nids** [comment]
cool, thanks for the feedback.

**Comment by 3nids** [comment]
discussion with Martin went well, here is the paste: http://pastebin.com/1Mj1DGFM

node tool will have both behavior (drag/drop and click/click)
a QEP will be issued by Martin
should land in 2.16

**Comment by vpicavet** [comment]
WIP, a prototype as Python plugin is almost done by Martin. Next will be a QEP and c++ port if relevant.

**Comment by vpicavet** [comment]
Plugin version available here : https://github.com/wonder-sk/CadNodeTool

**Comment by vpicavet** [comment]
Please test and report feedback on the plugin

**Comment by dsavary** [comment]
We test the plugin CadNodeTool. This tool is very appreciated by the users. The functionning of snapping is more evident and more fast than the basic node tool. The possibiliy to move several objets (the line and the point on line) all at once is useful.
Will this tool be soon included in QGIS core ? 
Do you think that the tool "Cadnodetool" will be merged with the basic "node tool" ?

**Comment by vpicavet** [comment]
See #121
