### ISSUE TITLE
Finalize a workflow for GPS data import

### ISSUE THREAD

**Issue by vpicavet** [qwat/QWAT#80]
We want to be able to import GPS data. As for now, the workflow for this feature is not clear.
A first step is therefore to refine the data import workflow, with inputs, potentially data processing, and results.  Guidelines for a GUI would be nice to have too.

Then we will be able to either implement a specific plugin, or describe the steps to achieve the workflow given existing qgis tools.

**Comment by vpicavet** [comment]
From various user inputs, a spec document has been written ( offline french only).

Summary of the main points for this document : 

* field survey with GPS come from GPS/GNSS or tacheometer, stored in CSV files, SHP or ASCII files
* the *survey_point* table is used to load this raw data ( some specific *usr_* fields could be added to it if needed)
* a mapping scheme enables to transform this data to objects in the model
* mapping schemes can be stored in db or file and chosen/shared by the user
* actions and errors should be logged
* import statistics should be available
* import atomicity should be a parameter ( full rollback on failure or insert valid only)
* update mode can be chosen ( if X, Y are the same, optionnaly Z too)

As for a new solution, we would do a 2-step importer ( import raw field measurements & dispatch them to objects), with a GUI wrapper around it so as to also have a simple 1-step import tool.

We will drop GSI file format support and only have CSV/TSV or SHP ( or other QGIS native formats)

Components would therefore be : 
1. An import plugin to add input files to the survey_point table
2. A data mapping plugin to allow for data dispatch in the model.
3. A plugin with a full GUI wrapper around these features

As for 2. we should check if using Virtual Layers and/or QGIS expressions could fasten development and add more genericity. Writing 2. as a Processing plugin would be an interesting option.

Next step : propose a global architecture and open corresponding issues, then implement the solution.

**Comment by haubourg** [comment]
for the record, specifications are stored in sahre platform here  https://www.oslandia.net/share/ws-qWAT/docs_specifications/fonctions_qgis_qwat/
