### ISSUE TITLE
End-user documentation « en Français »

### ISSUE THREAD

**Issue by vpicavet** [qwat/QWAT#82]
As our first users will be Francophones, we need a documentation in French.

As for documentation format, ReST/Sphinx/Readthedoc is proposed.

**Comment by tudorbarascu** [comment]
It would be nice if the documentation work-flow would encompass Transifex for translation in other languages

**Comment by tudorbarascu** [comment]
I can help in translation to English if the documentation base will be in French but I think the project would gain better traction if the base would be in English and the French added immediately through Transifex.
I am offering to support this workflow by:
- writing documentation in English
- help French documentation writers that don't know English and transform their French documentation to English and into the sphinx-docs format.

**Comment by haubourg** [comment]
Doc is already in French. I close that and create a new specific issue for Translation using transifex.
