### ISSUE TITLE
Fix QGIS bug on linked widgets for materials

### ISSUE THREAD

**Issue by vpicavet** [qwat/QWAT#85]
@3nids found a bug which needs to be solved, regarding the linked widget, appearing when using the GUI for materials.

@m-kuhn should be able to fix it then

**Comment by m-kuhn** [comment]
@vpicavet target 2.14? What exactly?

**Comment by 3nids** [comment]
There is a bug in the chained relation reference widget.
I still have to isolate the problem.
Will let you know, but fixing shouldn't be too long hopefully.

**Comment by vpicavet** [comment]
Any news on this one ? Reproduceable ?

**Comment by m-kuhn** [comment]
@3nids waiting for your feedback, ping me if you need my assistance.

**Comment by vpicavet** [comment]
@3nids Still present in 2.16 ?

**Comment by 3nids** [comment]
I just tried to use the custom widget in QtDesigner to use relation reference widget.
When saving the UI, QtDesigner crashes with this output
```
QObject::connect: Cannot connect (null)::featureDeleted( QgsFeatureId ) to QgsVectorLayerCache::featureDeleted( QgsFeatureId )
QObject::connect: Cannot connect (null)::featureAdded( QgsFeatureId ) to QgsVectorLayerCache::onFeatureAdded( QgsFeatureId )
QObject::connect: Cannot connect (null)::layerDeleted() to QgsVectorLayerCache::layerDeleted()
[New Thread 0x7ffee2fd8700 (LWP 5528)]
[New Thread 0x7fff29a0d700 (LWP 5527)]
[New Thread 0x7fff2ad68700 (LWP 5526)]
[New Thread 0x7fff2b772700 (LWP 5524)]
[New Thread 0x7fff320e1700 (LWP 5522)]
[New Thread 0x7fffbbc0a700 (LWP 5519)]

Program received signal SIGSEGV, Segmentation fault.
0x00007fffd7eaf700 in QgsVectorLayer::geometryType() const () from /lib/libqgis_core.so.2.15.0
```

@m-kuhn any idea?

**Comment by m-kuhn** [comment]
Do you have a stack trace?

**Comment by 3nids** [comment]
fixed in https://github.com/qgis/QGIS/commit/76bf6e0dc6cf7a1c84a3d0cc4fe7b8c1032e8eb0 thanks
testing the widget now

**Comment by 3nids** [comment]
working well apparently.
reused in https://github.com/qwat/QWAT/commit/3fe5fcac27b6edc521f6d60f2b7d1287bbbbf674
