### ISSUE TITLE
Mass-editing of attributes

### ISSUE THREAD

**Issue by vpicavet** [qwat/QWAT#86]
We want to be able to modify attributes for multiple objects, in a single operation.

There is a core QEP open, with specifications from @andreasneumann

**Comment by 3nids** [comment]
project is sponsored by Basel Stadt and will land in 2.16.
@nyalldawson is the deveoper.
will see if we can combine directly with #88

**Comment by 3nids** [comment]
I asked nyall for an offer

**Comment by andreasneumann** [comment]
Hi Denis, 

We (the Kanton Zug) also have interest in this functionality (search in
multiple fields directly from the form view). 

I would like to be informed about the specification. 

Would the result of the search be a filtered set or selection or let the
user decide if he wants to filter or select? 

Andreas 

On 2016-02-10 09:51, Denis Rouzaud wrote: 

> I asked nyall for an offer 
> 
> --
> Reply to this email directly or view it on GitHub [1].

  

Links:
------
[1] https://github.com/qwat/QWAT/issues/86#issuecomment-182257176

**Comment by 3nids** [comment]
My first thought is that we have a check box in front of each widget allow to use it or not in the search. It would be an "AND" filter.
Then, you would have "set as selection" and "add (/remove) to (/from) selection" buttons.
Add to selection would be the way of creating "OR" filters.

But I have no strong opinion on this. Let's keep in touch with Nyall to define this.

**Comment by andreasneumann** [comment]
Will you do a specification document where we all can review/comment? E.g. on Google docs or on Github Wiki?

**Comment by 3nids** [comment]
I am waiting on Nyall's opinion and start something then.
I just created it, so if you want to write anything down, you can start straight ahead.
https://docs.google.com/document/d/1OBis2-WM95PJEKJ-V9VA4NDx_kyHFWAsoLfl2s-MApw

**Comment by vpicavet** [comment]
See : https://github.com/qgis/QGIS-Enhancement-Proposals/issues/55

**Comment by vpicavet** [comment]
Implemented and pushed in qgis/QGIS/pull/2995

Thanks Nyall and Kanton Basel Stadt !
