### ISSUE TITLE
Multi-attributes filtering with GUI

### ISSUE THREAD

**Issue by vpicavet** [qwat/QWAT#88]
We would like to be able to search for features with multi-attributes filters. As for now the GUI available is not really straightforward to use ( attribute table).

The idea would be to use the mass-attribute features ( #86 ) and implement a GUI on top of this to allow for data filtering given multiple attributes. It would reuse the widgets dedicated to each field for a better integration with the rest of the QGIS features.

**Comment by 3nids** [comment]
https://github.com/qgis/QGIS-Enhancement-Proposals/issues/55

**Comment by 3nids** [comment]
multi attribute editing has been merged in master

now, for multi attribute filtering, this document gathers the ideas
https://docs.google.com/document/d/1OBis2-WM95PJEKJ-V9VA4NDx_kyHFWAsoLfl2s-MApw/edit#

Nyall will do an offer and the idea is to rush to merge this in 2.16 already.
Zug has no more money for this. I will probably ask the CH user group but there many demand for support lately, hence I don't give much chance t raise money for this.

I think we'll have to pay a bit for this one. Is this OK if QWAT participates to this dev?
(still waiting for the offer)

**Comment by vpicavet** [comment]
This has to be discussed with other qwat funders. Let me know when you have an offer so that I can integrate into funding documents.

**Comment by vpicavet** [comment]
This has been implemented by Nyall recently. Should be in master in time for 2.16

**Comment by vpicavet** [comment]
Implemented in 2.16
