### ISSUE TITLE
Default sets of values for attributes

### ISSUE THREAD

**Issue by vpicavet** [qwat/QWAT#92]
When editing objects, we often reuse recurring sets of values. It would be great to be able to save them somewhere as default values sets, so as not to have to re-enter these values each time.

**Comment by haubourg** [comment]
With constraint and default values in forms, editing can be much more simple. 
Still, having some "autofill feature" just like we have in modern web browser would be a time saver

**Comment by haubourg** [comment]
Hum, just the very old editing option of QGIS "remenber last values in forms" is a first efficient step. 
Going further could be storing "edit session profiles" with default templates for all forms.

**Comment by haubourg** [comment]
@qwat-board closing the issue by lack of feedback. Please reopen if necessary.

**Comment by dsavary** [comment]
The idea is to have a tool for the user to configure a set of default values on different layer. The user can define et change the diverse values depending on the work that the user should do.
For now, the plugin "Autofield" allow to do a part of this process. 
Needs for improvement : 
- show the value on the the feature form before saving the new feature.
- Define several value on the same attribute
