### ISSUE TITLE
Extract data from qwat

### ISSUE THREAD

**Issue by ponceta** [qwat/QWAT#94]
We're facing difficullties to make standard exports from qwat to the outside world.

Theses problems appear at least on shp and dxf exports.

E.g. on the pipe layer:

> L'export du fichier vectoriel a échoué.
Erreur : Erreurs d'écriture d'entité :
Entité géométrique non importée (Erreur OGR : Field geometry_1 of width 255 truncated to 254.)
Entité géométrique non importée (Erreur OGR : Field geometry_1 of width 255 truncated to 254.)
Entité géométrique non importée (Erreur OGR : Field geometry_1 of width 255 truncated to 254.)
...

Mainly due to the size of fields (as it seems).

**Comment by 3nids** [comment]
That's because you're trying to export the alternative geometry columns to the desired output. Either you ogr2ogr for shapes or QGIS' custom DXF export, and in both cases select only appropriate columns

**Comment by ponceta** [comment]
Ok, ty!
